import type { EmailTemplateDef } from '../blocks/component-library.types';

export const PREMADE_TEMPLATES: EmailTemplateDef[] = [
  {
    id: 'sys-tmpl-weekly-digest',
    name: 'סיכום שבועי',
    description: 'מייל סיכום שבועי הכולל כתבות, אקורדים, הופעות, פודקאסטים ופרופיל מומלץ',
    category: 'שבועי',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-music-news',
    name: 'חדשות מוזיקה',
    description: 'מייל חדשות מוזיקה עם כתבות נבחרות',
    category: 'תוכן',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-new-chords',
    name: 'אקורדים חדשים',
    description: 'מייל עם אקורדים חדשים שנוספו לאתר',
    category: 'תוכן',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-upcoming-events',
    name: 'הופעות קרובות',
    description: 'מייל עם הופעות קרובות',
    category: 'אירועים',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-new-podcasts',
    name: 'פודקאסטים חדשים',
    description: 'מייל עם פרקי פודקאסט חדשים',
    category: 'תוכן',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-single-recommendation',
    name: 'המלצת תוכן',
    description: 'מייל המלצה על תוכן בודד',
    category: 'שיווק',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-artist-promo',
    name: 'קידום אמן',
    description: 'מייל קידום לאמן חדש או מומלץ',
    category: 'שיווק',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-index-profiles',
    name: 'פרופילים מהאינדקס',
    description: 'מייל קידום פרופילים מאינדקס עולם המוזיקה',
    category: 'שיווק',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-site-members',
    name: 'הודעה לחברי האתר',
    description: 'מייל לחברי האתר עם עדכונים חשובים',
    category: 'תקשורת',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-marketing',
    name: 'מייל שיווקי',
    description: 'תבנית מייל שיווקי כללית',
    category: 'שיווק',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-advertising',
    name: 'מייל פרסומי',
    description: 'תבנית מייל פרסומי עם באנרים',
    category: 'שיווק',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sys-tmpl-blank-branded',
    name: 'תבנית ריקה ממותגת',
    description: 'מייל ריק עם Header וFooter ממותגים',
    category: 'בסיס',
    source: 'system',
    blocks: [],
    createdAt: '2026-01-01T00:00:00Z',
  },
];
