import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Lang = 'he' | 'en';

const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  he: {
    'nav.home': 'בית',
    'nav.chords': 'אקורדים',
    'nav.news': 'חדשות המוזיקה',
    'nav.index_full': 'אינדקס עולם המוזיקה',
    'nav.index_short': 'אינדקס',
    'user.admin': 'ניהול',
    'user.profile': 'הפרופיל שלי',
    'user.playlists': 'הרשימות שלי',
    'user.logout': 'התנתקות',
    'user.login': 'כניסה',
    'notif.loading': 'טוען התראות...',
    'notif.empty': 'אין התראות חדשות כרגע.',
    'notif.all': 'לכל ההתראות',
    'notif.close': 'סגור',
    'notif.center_empty': 'אין התראות כרגע.',
    'notif.clear_history': 'מחיקת ההיסטוריה',
    'notif.marketing': 'תוכן שיווקי',
    'notif.media': 'מצורפת מדיה',
    'notif.attachment': 'צירוף',
    'notif.error': 'לא הצלחנו לטעון התראות.',
    'notif.general_report_title': 'הודעה כללית למערכת',
    'footer.home': 'דף הבית',
    'footer.chords': 'אקורדים',
    'footer.index': 'אינדקס',
    'footer.music_news': 'חדשות מוזיקה',
    'footer.artists': 'דף אמנים',
    'footer.events': 'דף הופעות',
    'footer.articles': 'כתבות תוכן',
    'footer.playlists': 'מאגר רשימות שמורות',
    'footer.chord_dict': 'מילון אקורדים',
    'footer.random_song': 'שיר בהפתעה',
    'footer.tuner': 'כיוון גיטרה ויוקלילי',
    'footer.newsletter_title': 'הישאר מעודכן',
    'footer.newsletter_sub': 'שירים, אמנים וכתבות ישירות למייל',
    'footer.newsletter_placeholder': 'כתובת מייל',
    'footer.newsletter_btn': 'הרשמה',
    'footer.acum': 'אתר זה פועל ברשיון אקום',
    'footer.copyright': '© אקורדישקייט. כל הזכויות שמורות',
    'footer.rights_notice': 'אתר זה מכבד זכויות יוצרים — באם זכויותכם נפגעו',
    'footer.rights_resolve': 'להסדרת העניין',
    'footer.advertising': 'לפרסום ושיתופי פעולה —',
    'footer.contact': 'צרו קשר',

    // Song page
    'song.chords_subtitle': 'אקורדים לשיר',
    'song.lyrics': 'מילים:',
    'song.music': 'לחן:',
    'song.add_to_playlist': 'הוסף לרשימה',
    'song.share': 'שתף',
    'song.print': 'הדפס',
    'song.report_error': 'דווח על טעות',
    'song.key_prefix': 'סולם:',
    'song.easy_version': 'גרסה קלה',
    'song.auto_scroll': 'גלילה אוטומטית',
    'song.chord_diagrams_title': 'תרשימי האקורדים בשיר',
    'song.chord_diagrams_sub': 'כאן מוצגים כל האקורדים שמופיעים בשיר לפי הכלי שבחרת.',
    'song.capo_prefix': 'קאפו שריג',
    'song.capo_suffix': 'לנגינה בסולם המקורי',
    'song.rate_title': 'דרג את השיר',
    'song.rating_1': '1 כוכב — גרוע',
    'song.rating_2': '2 כוכבים — לא טוב',
    'song.rating_3': '3 כוכבים — בסדר',
    'song.rating_4': '4 כוכבים — טוב',
    'song.rating_5': '5 כוכבים — מצוין',
    'song.rating_poor': 'גרוע',
    'song.rating_not_good': 'לא טוב',
    'song.rating_ok': 'בסדר',
    'song.rating_good': 'טוב',
    'song.rating_excellent': 'מצוין!',
    'song.login_to_rate': 'התחבר כדי לדרג',
    'song.has_sheet_music': 'לשיר זה יש תווים',
    'song.go_to_sheet_music': 'למעבר לתווים',
    'song.need_help_teacher': 'צריכים עזרה עם הנגינה? המורים שלנו ישמחו לעזור לכם',
    'song.find_teacher': 'מצא מורה',
    'song.more_by_artist': 'עוד אקורדים לשירים של',
    'song.loading': 'טוען...',
    'song.loading_song': 'טוען שיר...',
    'song.try_again': 'נסה שוב',
    'song.you_might_like': 'שירים שאולי יעניינו אותך',
    'song.popular_this_week': 'הכי נצפים השבוע',
    'song.no_more_songs': 'אין כרגע שירים נוספים להצגה',
    'song.uploaded_by': 'הועלה על ידי',
    'song.open_youtube': 'פתח ביוטיוב',
    'song.open_pdf': 'פתח קובץ PDF',
    'song.open_full': 'פתח קובץ מלא',
    'song.link_copied': 'הקישור הועתק!',
    'song.known_all': 'אתה יודע לנגן את כל האקורדים בשיר',
    'song.missing_chords': 'חסרים לך',
    'song.missing_chords_suffix': 'אקורדים',
    'song.to_play_song': 'כדי לנגן את השיר הזה עם האקורדים שבחרת',
    'song.need_to_learn': 'צריך ללמוד:',
    'song.close': 'סגור',
    'song.instr_piano': 'פסנתר',
    'song.instr_guitar': 'גיטרה',
    'song.instr_ukulele': 'יוקלילי',
    'song.instr_lyrics': 'מילים בלבד',
    'song.transpose_down': 'הורד חצי טון',
    'song.transpose_up': 'העלה חצי טון',
    'song.transpose_reset': 'אפס טרנספוזיציה',
    'song.font_decrease': 'הקטן טקסט',
    'song.font_increase': 'הגדל טקסט',
    'song.scroll_slow': 'האט',
    'song.scroll_fast': 'האץ',
    'song.scroll_stop': 'עצור',
    'song.day_mode': 'מצב יום',
    'song.night_mode': 'מצב לילה',
    'song.show_diagrams': 'הצג תרשימי אקורדים',
    'song.sheet_music_alt': 'תווים לשיר',
    'song.known_chords_info': 'המידע מחושב לפי האקורדים שסימנת שאתה יודע לנגן. לפי זה מוצג כמה אקורדים חסרים לך כדי לנגן את השיר.',

    // Chords page
    'chords.title': 'אקורדים',
    'chords.subtitle': 'מאגר האקורדים הגדול והראשון מסוגו במוזיקה היהודית',
    'chords.search_placeholder': 'חפש שיר, אמן או מילים...',
    'chords.sort_newest': 'חדש → ישן',
    'chords.sort_most_viewed': 'הכי נצפה',
    'chords.sort_az': 'א–ת',
    'chords.songs_i_can_play': 'שירים שאני יודע לנגן',
    'chords.chord_dictionary': 'מילון האקורדים',
    'chords.tuner': 'כיוון גיטרה ויוקלילי',
    'chords.random_song': 'שיר בהפתעה',
    'chords.known_filter_title': 'שירים שקרובים לאקורדים שאני יודע לנגן',
    'chords.known_filter_sub': 'החישוב בודק את האקורדים שסימנת מול האקורדים בכל שיר. אפשר להוסיף אקורדים דרך סימון + בתרשים אקורד או דרך הפרופיל.',
    'chords.sort_exact': 'בדיוק כמו שאני יודע לנגן',
    'chords.sort_closest': 'הכי קרוב למה שאני יודע',
    'chords.sort_popular': 'פופולרי',
    'chords.clear_filters': 'נקה סינונים',
    'chords.results_prefix': 'נמצאו',
    'chords.results_suffix': 'תוצאות',
    'chords.loading': 'טוען...',
    'chords.no_results': 'לא נמצאו תוצאות',
    'chords.prev': 'הקודם',
    'chords.next': 'הבא',
    'chords.section_recent': 'נוספו לאחרונה',
    'chords.section_popular': 'פופולאריים עכשיו',
    'chords.section_most_viewed': 'הנצפים ביותר',
    'chords.section_dont_miss': 'לא תרצו לפספס',
    'chords.section_recently_viewed': 'צפית לאחרונה',
    'chords.section_all': 'כל האקורדים',

    // Profile page
    'profile.title': 'הפרופיל שלי',
    'profile.subtitle': 'פרטים אישיים לניהול החשבון — אינם מוצגים בפרופיל הציבורי',
    'profile.level': 'דרגה',
    'profile.completion_title': 'עוד כמה פרטים קטנים להשלמת הפרופיל',
    'profile.completion_sub': 'כדי שנוכל להציג לכם תוצאות מדויקות יותר',
    'profile.completion_cta': 'להשלמת הפרטים <',
    'profile.no_page': 'עדיין אין לך דף באתר',
    'profile.add_page': 'הוסף דף +',
    'profile.manage_page_title': 'ניהול הדף שלך באתר',
    'profile.manage_page_sub': 'העמוד שמוצג לחברי האתר',
    'profile.edit_page': 'ערוך דף',
    'profile.view_page': 'צפה בדף',
    'profile.page_type': 'סוג דף:',
    'profile.status': 'סטטוס:',
    'profile.saving': 'שומר...',
    'profile.disable_page': 'כבה דף',
    'profile.enable_page': 'הפעל דף',
    'profile.change_account_type': 'לשינוי סוג חשבון >',
    'profile.subscriptions_title': 'מינויים ותשלומים',
    'profile.subscriptions_sub': 'ניהול המינויים שלך והיסטוריית תשלומים',
    'profile.upgrade': 'שדרג מנוי',
    'profile.manage': 'לניהול',
    'profile.account': 'חשבון:',
    'profile.known_chords_title': 'האקורדים שאני יודע לנגן:',
    'profile.adding': 'מוסיף...',
    'profile.basics_added': 'הבסיסיים נוספו',
    'profile.add_basics': 'הוסף בסיסיים',
    'profile.removing': 'מוחק...',
    'profile.remove_all': 'מחק הכל',
    'profile.no_chords': 'עדיין לא סומנו אקורדים',
    'profile.my_content_title': 'תכנים שהעליתי:',
    'profile.content_chords': 'אקורדים',
    'profile.content_articles': 'כתבות ובלוג',
    'profile.content_events': 'הופעות',
    'profile.pending': 'ממתין לאישור',
    'profile.no_songs': 'עוד לא העלית אקורדים',
    'profile.no_articles': 'עוד לא העלית כתבות או בלוג',
    'profile.no_events': 'עוד לא העלית הופעות',
    'profile.show_more': 'הצג עוד',
    'profile.go_to_playlists': 'למעבר לרשימות שמורות',
    'profile.modal_title': 'השלמת פרטים אישיים',
    'profile.modal_sub': 'הפרטים לא יוצגו בפרופיל הציבורי',
    'profile.label_email': 'מייל',
    'profile.label_phone': 'טלפון',
    'profile.label_address': 'כתובת',
    'profile.label_birthdate': 'תאריך לידה',
    'profile.address_placeholder': 'עיר, רחוב ומספר',
    'profile.save': 'שמור',
    'profile.instrument_guitar': 'גיטרה',
    'profile.instrument_piano': 'פסנתר',
    'profile.instrument_ukulele': 'יוקלילי',
    'profile.level_0': 'משתמש רשום',
    'profile.level_1': 'מתחיל',
    'profile.level_2': 'תורם',
    'profile.level_3': 'תורם מוביל',
    'profile.sub_free': 'חינמי',
    'profile.sub_active': 'פעיל',
    'profile.sub_trial': 'ניסיון חינם',
    'profile.sub_pending': 'ממתין לתשלום',
    'profile.sub_cancelled': 'בוטל',
    'profile.sub_expired': 'פג תוקף',
    'profile.sub_suspended': 'מושהה',
    'profile.sub_inactive': 'לא פעיל',
    'profile.page_active': 'העמוד פעיל',
    'profile.page_pending_approval': 'ממתין לאישור',
    'profile.page_off': 'העמוד כבוי',
    'profile.page_type_artist': 'אמן',
    'profile.page_type_teacher': 'מורה למוזיקה',
    'profile.page_type_provider': 'בעל מקצוע',
    'profile.page_type_user': 'משתמש רגיל',
    'profile.type_blog': 'בלוג',
    'profile.type_article': 'כתבה',
    'profile.confirm_remove_all': 'למחוק את כל האקורדים שסומנו עבור',
    'profile.disconnecting': 'מנתק...',

    // FAB / Quick-Add Assistant
    'fab.root_question': 'איזה תוכן תרצה להוסיף לאתר?',
    'fab.root_helper': 'הוספת תוכן לאתר מתוגמלת בתג מיוחד ואפשרויות בלעדיות באתר לחברים מתקדמים.',
    'fab.content_question': 'מעולה, איזה תוכן תרצה להוסיף?',
    'fab.index_question': 'הבנתי, איזה פרופיל תרצה לאינדקס?',
    'fab.artist_question': 'איך תרצה להוסיף את האמן?',
    'fab.song_selected': 'מעולה, נמשיך להוספת אקורדים.',
    'fab.chord_request_question': 'איזה שיר תרצה שנוסיף אקורדים עבורו?',
    'fab.opt_chords': 'אקורדים',
    'fab.opt_content': 'תוכן',
    'fab.opt_event': 'הופעה',
    'fab.opt_index': 'פרופיל לאינדקס',
    'fab.opt_artist': 'אמן',
    'fab.opt_chord_request': 'לבקש אקורדים לשיר',
    'fab.opt_contact_form': 'יצירת קשר',
    'fab.opt_report': 'דיווח',
    'fab.opt_news': 'חדשות מוזיקה',
    'fab.opt_blog': 'תוכן אחר',
    'fab.opt_teacher': 'מורה למוזיקה',
    'fab.opt_other': 'אחר',
    'fab.opt_artist_account': 'להפוך לחשבון אמן',
    'fab.opt_artist_community': 'להוסיף אמן ללא בעלות חשבון',
    'fab.secondary_label': 'או שתרצו',
    'fab.back': 'חזרה',
    'fab.submitting': 'שולח...',
    'fab.submit_approval': 'שליחה לאישור',
    'fab.submit_request': 'שליחת בקשה',
    'fab.submit_contact': 'שליחה',
    'fab.close': 'סגירה',
    'fab.uploading': 'מעלה...',
    'fab.upload_image': 'העלאת תמונה',
    'fab.image_link': 'קישור לתמונה',
    'fab.use_video_thumb': 'לקחת מהוידאו',
    'fab.optional_label': 'עוד כמה פרטים להשלמת החוויה, לא חובה',
    'fab.optional_hint': 'לא חובה',
    'fab.article_title': 'כותרת',
    'fab.article_content': 'תוכן',
    'fab.article_subtitle': 'כותרת משנה',
    'fab.author_name': 'שם הכותב',
    'fab.short_desc': 'תקציר קצר',
    'fab.video_youtube': 'וידאו מיוטיוב',
    'fab.video_note': 'אפשר לצרף קישור לוידאו',
    'fab.image': 'תמונה',
    'fab.image_note_article': 'אפשר להעלות, להדביק קישור או לקחת מהוידאו',
    'fab.image_note_event': 'אפשר להעלות תמונה או להדביק קישור',
    'fab.tag_content': 'שיוך התוכן למעלה התוכן',
    'fab.tag_myself': 'האם לתייג את התוכן על שמך',
    'fab.tag_myself_yes': 'כן, לתייג על שמי',
    'fab.filter_all': 'כולם',
    'fab.filter_teachers': 'מורים',
    'fab.filter_providers': 'נותני שירות',
    'fab.filter_artists': 'אמנים',
    'fab.filter_users': 'חברים רגילים',
    'fab.sort_name': 'מיון לפי שם',
    'fab.sort_type': 'מיון לפי סוג',
    'fab.search_profile': 'חפש לפי שם ברשימה שנבחרה',
    'fab.search_artist': 'חפש אמן לתיוג',
    'fab.no_results': 'לא נמצאו תוצאות',
    'fab.no_artists': 'לא נמצאו אמנים',
    'fab.not_linked': ' · לא מקושר לחשבון',
    'fab.profile_type_artist': 'אמן',
    'fab.profile_type_user': 'חבר רגיל',
    'fab.profile_type_teacher': 'מורה',
    'fab.profile_type_provider': 'נותן שירות',
    'fab.profile_type_general': 'מורה / נותן שירות',
    'fab.event_ticket_link': 'לינק לכרטיסים',
    'fab.event_date': 'תאריך',
    'fab.event_tag_artist': 'תיוג אמן מהאתר',
    'fab.event_artist_type': 'אמן',
    'fab.event_name': 'כותרת ההופעה',
    'fab.event_artist_name': 'שם אמן',
    'fab.event_location': 'מיקום',
    'fab.event_price': 'מחיר',
    'fab.event_description': 'תיאור קצר',
    'fab.chord_song_name': 'שם השיר',
    'fab.chord_artist_name': 'שם האמן',
    'fab.contact_full_name': 'שם מלא',
    'fab.contact_email': 'אימייל',
    'fab.contact_subject': 'נושא',
    'fab.contact_select_subject': 'בחר נושא',
    'fab.contact_subject_general': 'שאלה כללית',
    'fab.contact_subject_tech': 'בעיה טכנית',
    'fab.contact_subject_partner': 'שיתוף פעולה',
    'fab.contact_subject_improve': 'הצעה לשיפור',
    'fab.contact_subject_other': 'אחר',
    'fab.contact_message': 'הודעה',
    'fab.contact_message_placeholder': 'כתבו את ההודעה כאן...',
    'fab.contact_attachments': 'קבצים מצורפים',
    'fab.contact_attach_file': 'צרף קובץ',
    'fab.success_song': 'השיר נשלח לאישור מנהל.',
    'fab.success_news': 'החדשה נשלחה לאישור מנהל.',
    'fab.success_article': 'התוכן נשלח לאישור מנהל.',
    'fab.success_event': 'ההופעה נשלחה לאישור מנהל.',
    'fab.success_chord_request': 'הבקשה נשלחה! נעשה כמיטב יכולתנו להוסיף את האקורדים בהקדם.',
    'fab.success_contact': 'ההודעה נשלחה! נחזור אליכם בהקדם.',

    // Shared UI
    'shared.ended': 'הסתיים',
    'shared.tickets': 'לכרטיסים',
    'shared.loading': 'טוען...',
    'shared.try_again': 'נסה שוב',
    'shared.show_more': 'הצג עוד',
    'shared.cancel': 'ביטול',
    'shared.save': 'שמור',
    'shared.close': 'סגור',
    'shared.songs_suffix': 'שירים',
    'shared.prev': 'הקודם',
    'shared.next': 'הבא',
    'shared.search': 'חיפוש',
    'shared.reset': 'איפוס',
    'shared.saving': 'שומר...',

    // Song card
    'song_card.label': 'אקורדים לשיר',
    'song_card.unknown_artist': 'אמן לא ידוע',
    'song_card.all_known': 'כל האקורדים מוכרים',
    'song_card.missing_one': 'חסר אקורד אחד',
    'song_card.missing_prefix': 'חסרים',
    'song_card.missing_suffix': 'אקורדים',
    'song_card.info_all': 'לפי האקורדים שסימנת שאתה יודע לנגן, כל האקורדים בשיר מוכרים לך.',
    'song_card.info_missing_prefix': 'לפי האקורדים שסימנת שאתה יודע לנגן, חסרים לך',
    'song_card.info_missing_suffix': 'אקורדים כדי לנגן את השיר.',

    // Report modal
    'report.title': 'דיווח על בעיה',
    'report.sent': 'הדיווח נשלח!',
    'report.thanks': 'תודה, נטפל בכך בהקדם',
    'report.what_problem': 'מה הבעיה?',
    'report.detail': 'פירוט',
    'report.placeholder': 'תאר את הבעיה בקצרה...',
    'report.sending': 'שולח...',
    'report.submit': 'שליחה',
    'report.type_error': 'טעות בתוכן',
    'report.type_inappropriate': 'תוכן לא ראוי',
    'report.type_other': 'אחר',
    'report.validation': 'נא לתאר את הבעיה בעשרה תווים לפחות',
    'report.error_submit': 'שגיאה בשליחת הדיווח',

    // Pagination
    'paginate.showing': 'מציג',
    'paginate.of': 'מתוך',
    'paginate.first_page': 'עמוד ראשון',
    'paginate.prev_page': 'עמוד קודם',
    'paginate.next_page': 'עמוד הבא',
    'paginate.last_page': 'עמוד אחרון',

    // Auth modal
    'auth.login_title': 'כניסה:',
    'auth.register_title': 'הרשמה:',
    'auth.username': 'שם משתמש',
    'auth.email': 'מייל',
    'auth.password': 'סיסמה',
    'auth.google_login': 'התחבר עם Google',
    'auth.google_register': 'הירשם עם Google',
    'auth.terms': 'בהרשמה לאתר אני מאשר/ת את תקנון האתר ומסכים/ה לקבל עדכונים ותוכן שיווקי במייל.',
    'auth.terms_link': 'תקנון האתר',
    'auth.submit_login': 'היכנס ←',
    'auth.submit_register': 'המשך ←',
    'auth.no_account': 'עדיין אין לך חשבון?',
    'auth.register_link': 'הירשם',
    'auth.has_account': 'כבר יש לך חשבון?',
    'auth.login_link': 'היכנס',
    'auth.password_hint': '8+ תווים, אות גדולה, ספרה ותו מיוחד (@$!%*?&#)',

    // Forgot password
    'forgot.title_request': 'שחזור סיסמא',
    'forgot.title_verify': 'הזנת סיסמא חדשה',
    'forgot.subtitle_request': 'נשלח לך קוד אימות לאיפוס הסיסמא',
    'forgot.subtitle_verify': 'הזן את הקוד שקיבלת וסיסמא חדשה',
    'forgot.username_label': 'שם משתמש או אימייל',
    'forgot.username_placeholder': 'שם משתמש או כתובת מייל',
    'forgot.recovery_method': 'שיטת שחזור',
    'forgot.send_code': 'שלח קוד אימות',
    'forgot.code_label': 'קוד אימות',
    'forgot.code_placeholder': 'הזן את הקוד שקיבלת',
    'forgot.new_password': 'סיסמא חדשה',
    'forgot.requirements_title': 'הסיסמא חייבת לכלול:',
    'forgot.strength_weak': 'חלשה',
    'forgot.strength_medium': 'בינונית',
    'forgot.strength_strong': 'חזקה',
    'forgot.confirm_password': 'אימות סיסמא',
    'forgot.reset': 'אפס סיסמא',

    // Additional details modal
    'details.step1_title': 'כמה פרטים קטנים להשלמת החוויה',
    'details.step1_sub': 'מנגנ/ת על משהו?',
    'details.piano': 'קלידים',
    'details.guitar': 'גיטרה',
    'details.other_instrument': 'אחר',
    'details.no_instrument': 'לא מנגנ/ת',
    'details.beginner': 'מתחיל/ה',
    'details.intermediate': 'מתקדם/ת',
    'details.professional': 'מקצועי/ת',
    'details.continue': 'המשך <',
    'details.skip': 'דלג לאתר',
    'details.step2_title': 'איך תרצה/י להשתמש באקורדישקייט?',
    'details.step2_sub': 'ניתן לשנות גם אחר כך',
    'details.regular_user': 'משתמש רגיל',
    'details.regular_desc': 'לגלות מוזיקה, לנגן, ללמוד ולהנות',
    'details.professional_user': 'בעל מקצוע',
    'details.professional_desc': 'להציע שירותים מוזיקליים ולהופיע באינדקס',
    'details.teacher_user': 'מורה',
    'details.teacher_desc': 'להציע שיעורים ולהופיע באינדקס המורים',
    'details.artist_user': 'אמן',
    'details.artist_desc': 'לשתף תוכן ולנהל דף אמן משלך',

    // Home page
    'home.subtitle': 'הבית של המוזיקה היהודית.',
    'home.search_placeholder': 'חפשו שירים, אקורדים, מילים, מורים, או כל דבר מהאתר',
    'home.search_songs': 'שירים ואקורדים',
    'home.search_artists': 'אמנים',
    'home.search_articles': 'כתבות',
    'home.search_teachers': 'מורים',
    'home.search_professionals': 'בעלי מקצוע',
    'home.search_playlists': 'רשימות שמורות',
    'home.search_by_lyrics': 'שירים לפי מילות השיר',
    'home.search_deep_label': 'חיפוש עמוק',
    'home.searching_deep': 'מחפש במילות השיר...',
    'home.no_results': 'לא נמצאו תוצאות עבור',
    'home.quick_dict': 'למילון האקורדים ›',
    'home.quick_tuner': 'כיוון גיטרה ויוקלילי ›',
    'home.quick_artists': 'לרשימות האמנים ›',
    'home.news_title': 'חדשות המוזיקה',
    'home.news_link': 'לכל החדשות ‹',
    'home.promo_chords_title': 'אקורדים',
    'home.promo_chords_sub': 'מאגר האקורדים הגדול והראשון מסוגו במוזיקה היהודית',
    'home.promo_chords_link': 'לכל האקורדים ‹',
    'home.promo_chords_random': 'שיר בהפתעה',
    'home.recent_chords': 'אקורדים שהועלו לאחרונה',
    'home.popular_chords': 'אקורדים פופולאריים',
    'home.popular_artists': 'אמנים פופולאריים',
    'home.artists_link': 'לכל האמנים ‹',
    'home.teachers_title': 'מומלצי המערכת',
    'home.teachers_link': 'לאינדקס עולם המוזיקה',
    'home.default_teacher': 'מורה למוזיקה',
    'home.promo_index_title': 'אינדקס עולם המוזיקה',
    'home.promo_index_sub': 'המאגר הגדול לנותני שירות במוזיקה היהודית',
    'home.promo_index_link': 'לאינדקס ‹',
    'home.promo_index_join': 'הצטרף לאינדקס ‹',
    'home.professionals_title': 'בעלי מקצוע',
    'home.professionals_link': 'לכל בעלי המקצוע ‹',
    'home.default_pro': 'בעל מקצוע',
    'home.featured_title': 'מומלצי המערכת',
    'home.upcoming_events': 'הופעות קרובות',
    'home.events_link': 'לכל ההופעות ‹',
    'home.content_title': 'תוכן',
    'home.content_link': 'לכל התוכן ‹',

    // Notifications page
    'notif_page.eyebrow': 'מרכז התראות',
    'notif_page.title': 'כל העדכונים שלך במקום אחד',
    'notif_page.desc': 'כאן יופיעו אישורים, עדכוני סטטוס והודעות אישיות מהמערכת.',
    'notif_page.delete_all': 'מחיקת כל ההיסטוריה',
    'notif_page.loading': 'טוען התראות...',
    'notif_page.empty_title': 'אין התראות כרגע',
    'notif_page.empty_desc': 'כשיהיה עדכון חדש, הוא יופיע כאן.',
    'notif_page.marketing_tag': 'תוכן שיווקי',
    'notif_page.open_file': 'פתיחת קובץ מצורף',
    'notif_page.view': 'לצפייה בעדכון',
    'notif_page.delete_btn': 'מחיקת התראה',
    'notif_page.error': 'לא הצלחנו לטעון את ההתראות כרגע.',
    'notif_page.attach_default': 'צירוף',

    // Artists list
    'artists.label': 'אמנים',
    'artists.title': 'האמנים שלנו',
    'artists.site_count': 'אמנים באתר',
    'artists.search_placeholder': 'חפש אמן...',
    'artists.sort_az': 'א–ת',
    'artists.sort_popular': 'פופולרי',
    'artists.sort_new': 'חדשים',
    'artists.songs_suffix': 'שירים',
    'artists.empty': 'לא נמצאו אמנים',
    'artists.empty_search': 'נסה מילת חיפוש אחרת',

    // Events page
    'events.title': 'הופעות',
    'events.filter_upcoming': 'קרובות',
    'events.filter_all': 'הכל',
    'events.filter_past': 'שעברו',
    'events.empty': 'אין הופעות להצגה',
    'events.tickets': 'לכרטיסים',
    'events.tab_news': 'חדשות',
    'events.tab_blog': 'בלוג',
    'events.tab_events': 'הופעות',

    // Music news / Blog
    'news.load_failed': 'טעינת החדשות נכשלה. אנא בדקו את החיבור ונסו שנית.',
    'news.no_content': 'אין תוכן חדשות להצגה כרגע.',
    'blog.load_failed': 'טעינת הבלוג נכשלה. אנא בדקו את החיבור ונסו שנית.',
    'blog.no_content': 'אין פוסטים בבלוג להצגה כרגע.',

    // Playlists page
    'playlists.title': 'הרשימות שלי',
    'playlists.subtitle': 'מקום אחד לכל השמירות — שירים, אקורדים, כתבות ורשימות אישיות.',
    'playlists.community_desc': 'גלה רשימות שמשתמשים אחרים שיתפו עם הקהילה',
    'playlists.community_btn': 'מאגר רשימות קהילתי',
    'playlists.new_name_placeholder': 'שם הרשימה החדשה',
    'playlists.public': 'רשימה ציבורית',
    'playlists.private': 'רשימה פרטית',
    'playlists.create': 'צור רשימה',
    'playlists.new_btn': 'רשימה חדשה',
    'playlists.options': 'אפשרויות',
    'playlists.export_book': 'יצא כספר אקורדים',
    'playlists.duplicate': 'שכפל רשימה',
    'playlists.delete': 'מחק רשימה',
    'playlists.empty': 'עדיין אין רשימות',
    'playlists.saved_title': 'השמורים שלי',
    'playlists.articles_title': 'כתבות ותוכן',
    'playlists.saved_songs': 'שירים שמורים',
    'playlists.remove_saved': 'הסר מהשמורים',
    'playlists.empty_all_title': 'עדיין אין לך שמירות',
    'playlists.empty_all_text': 'שמור שירים, כתבות ותוכן כללי והם יופיעו כאן בצורה מסודרת.',
    'playlists.image_placeholder': 'הדבק כתובת URL של תמונה',
    'playlists.songs_count': 'שירים',
    'playlists.error_load': 'שגיאה בטעינת הרשימות',
    'playlists.error_name': 'יש להזין שם לרשימה',
    'playlists.error_create': 'שגיאה ביצירת הרשימה',
    'playlists.confirm_delete': 'למחוק את הרשימה?',
    'playlists.loading': 'טוען...',

    // Playlist detail
    'playlist.back': 'חזרה לרשימות',
    'playlist.default_badge': 'ברירת מחדל',
    'playlist.public': 'ציבורית',
    'playlist.private': 'פרטית',
    'playlist.public_hint': 'הרשימה גלויה לכל משתמשי האתר',
    'playlist.private_hint': 'הרשימה גלויה רק לך',
    'playlist.chord_book_title': 'הפוך את הרשימה לספר אקורדים',
    'playlist.chord_book_desc': 'כל שירי הרשימה בתצוגת אקורדים, מוכנים להדפסה',
    'playlist.name_placeholder': 'שם הרשימה',
    'playlist.desc_placeholder': 'תיאור (אופציונלי)',
    'playlist.image_placeholder': 'הדבק URL של תמונה',
    'playlist.empty': 'הרשימה ריקה',
    'playlist.empty_desc': 'הוסף שירים לרשימה מדף השיר',
    'playlist.col_song': 'שיר',
    'playlist.col_artist': 'אמן',
    'playlist.col_added': 'נוסף',
    'playlist.remove': 'הסר',
    'playlist.loading': 'טוען רשימה...',
    'playlist.error_load': 'שגיאה בטעינת הרשימה',
    'playlist.confirm_remove': 'להסיר שיר זה מהרשימה?',
    'playlist.confirm_delete': 'למחוק את הרשימה לצמיתות?',

    // Playlist popup
    'popup.title': 'ניהול שמירה',
    'popup.new_list': 'רשימה חדשה',
    'popup.name_placeholder': 'שם הרשימה החדשה',
    'popup.public': 'רשימה ציבורית',
    'popup.private': 'רשימה פרטית',
    'popup.create': 'צור רשימה',
    'popup.default_playlist': 'השמורים שלי',
    'popup.songs_suffix': 'שירים',
    'popup.community': 'מאגר רשימות',
    'popup.my_playlists': 'הרשימות שלי',
    'popup.done': 'בוצע',
    'popup.error_load': 'שגיאה בטעינת הרשימות',
    'popup.error_state': 'שגיאה בטעינת מצב השמירה',
    'popup.saved_default': 'השיר נשמר ב"השמורים שלי"',
    'popup.already_saved': 'השיר כבר שמור ב"השמורים שלי"',
    'popup.error_save': 'שגיאה בשמירת השיר',
    'popup.error_remove': 'לא ניתן להסיר את השיר',
    'popup.error_add': 'לא ניתן לשמור את השיר',
    'popup.error_playlist_add': 'לא ניתן להוסיף את השיר לרשימה',
    'popup.error_playlist_remove': 'לא ניתן להסיר את השיר מהרשימה',
    'popup.error_name': 'יש להזין שם לרשימה',
    'popup.error_create': 'שגיאה ביצירת הרשימה',
    'popup.created_ok': 'הרשימה נוצרה בהצלחה',
    'popup.error_song_added': 'הרשימה נוצרה אבל לא הצלחנו להוסיף אליה את השיר',

    // Chord dictionary
    'dict.all_roots': 'כל השורשים',
    'dict.all_types': 'כל הסוגים',
    'dict.title_guitar': 'מילון אקורדים לגיטרה',
    'dict.title_piano': 'מילון אקורדים לקלידים',
    'dict.title_ukulele': 'מילון אקורדים ליוקלילי',
    'dict.no_bass_chords': 'אקורדי סלאש עם צליל בס זה לא קיימים במאגר כרגע',
    'dict.no_chord_prefix': 'לא נמצא אקורד',
    'dict.no_chord_suffix': 'במאגר עבור הכלי הנוכחי',
    'dict.instr_guitar': 'גיטרה',
    'dict.instr_piano': 'קלידים',
    'dict.instr_ukulele': 'יוקלילי',
    'dict.playing': 'מנגן...',
    'dict.play_chord': 'השמע אקורד',
    'dict.known_yes': 'ברשימת האקורדים שאני יודע',
    'dict.known_no': 'הוסף לאקורדים שאני יודע',
    'dict.title_known': 'האקורד ברשימת האקורדים שאני יודע לנגן',
    'dict.title_unknown': 'להוספה לרשימת האקורדים שאני יודע לנגן',
    'dict.fingers_title': 'מספור אצבעות',
    'dict.finger_1': 'אצבע',
    'dict.finger_2': 'אמה',
    'dict.finger_3': 'קמיצה',
    'dict.finger_4': 'זרת',
    'dict.placement_title': 'הנחת אצבעות',
    'dict.piano_press': 'לחצו בו-זמנית על כל המקשים המסומנים בצהוב.',
    'dict.keys_title': 'מקשים לנגינה',
    'dict.title_filter': 'קלידים',
    'dict.notes_pre': 'האקורד',
    'dict.notes_mid': 'המוצג כאן מכיל את הצלילים:',
    'dict.root_pre': 'שורש האקורד הינו',
    'dict.scale_pre': 'הסולם ממנו לקוח האקורד הינו',
    'dict.scale_and': ', והדרגות מהסולם הן:',
    'dict.guitar_placement_pre': 'לנגינת האקורד',
    'dict.guitar_placement_mid': 'המוצג למעלה, יש להניח את האצבעות באופן הבא:',

    // Tuner page
    'tuner.hero_guitar': 'כיוון גיטרה',
    'tuner.hero_ukulele': 'כיוון יוקלילי',
    'tuner.sub': 'כיוון לפי שמיעה ועם מיקרופון',
    'tuner.guitar': 'גיטרה',
    'tuner.ukulele': 'יוקלילי',
    'tuner.instructions_ear': 'כיוון לפי שמיעה:',
    'tuner.instructions_text': 'לחצו על שם המיתר כדי לשמוע את הצליל הנכון שלו, ואז כווּנוּ את הגיטרה בסיבוב מפתחות הכיוון עד שהמיתר שלכם ישמע כמו הצליל שנשמע.',
    'tuner.guitar_ear_note': 'כיוון גיטרה דורש יכולת שמיעה מוסיקלית ברמה בסיסית.',
    'tuner.connecting': 'מתחבר...',
    'tuner.stop_mic': 'עצור מיקרופון',
    'tuner.start_mic': 'כיוון עם מיקרופון',
    'tuner.tuning_string': 'מכוונים מיתר',
    'tuner.pick_string': 'בחרו מיתר מהרשימה למטה ונגנו אותו',
    'tuner.listening': 'מאזין...',
    'tuner.in_tune': 'מכוון ✓',
    'tuner.guide_title_guitar': 'כיוון גיטרה סטנדרטי',
    'tuner.guide_title_ukulele': 'כיוון יוקלילי סטנדרטי',
    'tuner.guide_hint': 'כוונו כל מיתר עד שהצליל תואם לצליל שבכלי זה.',
    'tuner.guitar_guide': 'מיתר 6 הוא העבה ביותר (E2), מיתר 1 הוא הדק ביותר (E4).',
    'tuner.ukulele_guide': 'מיתר 4 הוא העבה ביותר (G4), מיתר 1 הוא הדק ביותר (A4).',
    'tuner.mic_denied': 'הגישה למיקרופון נדחתה. אפשרו גישה בהגדרות הדפדפן ונסו שוב.',
    'tuner.mic_error': 'לא ניתן לגשת למיקרופון. בדקו שהמכשיר מחובר ונסו שוב.',

    // Teachers page
    'teachers.upgrade_btn': 'השתדרג למורה',
    'teachers.search_placeholder': 'חיפוש לפי שם מורה או כלי נגינה...',
    'teachers.all_cities': 'כל הערים',
    'teachers.all_instruments': 'כל כלי הנגינה',
    'teachers.all_audiences': 'כל קהלי היעד',
    'teachers.all_languages': 'כל שפות ההוראה',
    'teachers.clear_filters': 'נקה סינונים',
    'teachers.loading': 'טוען מורים...',
    'teachers.results_count': 'מורים',
    'teachers.no_match': 'לא נמצאו מורים התואמים לחיפוש',
    'teachers.try_filter': 'נסה לשנות את הסינון',
    'teachers.featured': 'מורים מומלצים',
    'teachers.organ': 'מורים לאורגן',
    'teachers.sound': 'מורים לסאונד',
    'teachers.vocal': 'מורים לפיתוח קול',
    'teachers.more': 'עוד',
    'teachers.additional': 'מורים נוספים',
    'teachers.experience_suffix': 'שנות ניסיון',
    'teachers.no_teachers': 'אין מורים זמינים כרגע',
    'teachers.try_later': 'נסה שוב מאוחר יותר',
    'teachers.for_instrument': 'מורים ל',

    // Teacher detail page
    'teacher.featured_badge': 'מומלץ',
    'teacher.contact': 'ליצירת קשר',
    'teacher.gallery': 'גלריה',
    'teacher.testimonials': 'המלצות תלמידים',
    'teacher.content_title': 'תכנים שהעליתי',
    'teacher.chords': 'אקורדים',
    'teacher.articles': 'כתבות ותכנים',
    'teacher.student': 'תלמיד',
    'teacher.loading': 'טוען פרטי מורה...',
    'teacher.whatsapp_label': 'הודעה מהירה',
    'teacher.testimonial_n': 'המלצה',
    'teacher.testimonials_next': 'המלצות נוספות',
    'teacher.testimonials_prev': 'המלצות קודמות',
    'teacher.role_prefix': 'מורה ל',
    'teacher.role_generic': 'מורה למוזיקה',
    'teacher.experience_prefix': 'מעל ',
    'teacher.experience_suffix': 'שנות ניסיון',
    'teacher.info_education': 'השכלה',
    'teacher.info_lessons': 'סוגי שיעורים',
    'teacher.info_availability': 'זמינות',
    'teacher.info_hours': 'שעות פעילות',
    'teacher.info_price': 'מחירון',
    'teacher.info_specializations': 'התמחויות',
    'teacher.lang_hebrew': 'עברית',
    'teacher.lang_english': 'אנגלית',
    'teacher.lang_russian': 'רוסית',
    'teacher.lang_french': 'צרפתית',
    'teacher.lang_spanish': 'ספרדית',
    'teacher.lang_arabic': 'ערבית',
    'teacher.audience_children': 'ילדים',
    'teacher.audience_teenagers': 'נוער',
    'teacher.audience_adults': 'מבוגרים',
    'teacher.audience_seniors': 'גיל הזהב',
    'teacher.audience_beginners': 'מתחילים',
    'teacher.audience_intermediate': 'בינוניים',
    'teacher.audience_advanced': 'מתקדמים',
    'teacher.audience_professional': 'מקצועיים',
    'teacher.social_website': 'אתר',
    'teacher.social_link': 'קישור',
    'teacher.video_caption': 'סרטון היכרות',
    'teacher.whatsapp_msg': 'הי, הגעתי דרך אתר אקורדישקייט',

    // Articles list
    'articles.all_title': 'כל הכתבות',
    'articles.search_placeholder': 'חיפוש...',
    'articles.all_categories': 'כל הקטגוריות',
    'articles.all_types': 'כל הסוגים',
    'articles.count_suffix': 'כתבות',
    'articles.no_results': 'לא נמצאו כתבות',
    'articles.cat_general': 'כללי',
    'articles.cat_news': 'חדשות',
    'articles.cat_reviews': 'ביקורות',
    'articles.cat_interviews': 'ראיונות',
    'articles.cat_features': 'מאמרים',
    'articles.cat_live': 'כיסויי הופעות',
    'articles.cat_album_reviews': 'ביקורות אלבומים',
    'articles.cat_music_tech': 'טכנולוגיה מוזיקלית',
    'articles.cat_education': 'לימודי מוזיקה',
    'articles.cat_popular': 'פופולאריים',
    'articles.cat_clips': 'קליפים',
    'articles.cat_blog': 'בלוג',
    'articles.cat_opinion': 'דעה',
    'articles.cat_charts': 'מצעדים',
    'articles.cat_behind': 'מאחורי הקלעים',
    'articles.type_news': 'חדשות',
    'articles.type_blog': 'בלוג',

    // Chord dictionary extras
    'dict.no_bass': 'ללא בס',
    'dict.finger_name_1': 'אצבע מורה',

    // Artist create form
    'artist_create.badge': 'דף אמן',
    'artist_create.step_profile': 'פרופיל',
    'artist_create.step_links': 'קישורים',
    'artist_create.step_media': 'מדיה',
    'artist_create.form_steps': 'שלבי הטופס',
    'artist_create.success_title': 'דף האמן נשלח לבדיקה',
    'artist_create.success_text': 'הפרטים הועברו למנהל. אם תרצה, אפשר עכשיו להמשיך לבחירת מנוי כדי לפתוח אפשרויות מתקדמות בדף.',
    'artist_create.choose_plan': 'בחירת מנוי',
    'artist_create.finish': 'סיום',
    'artist_create.step1_intro': 'נתחיל מהלב של הפרופיל, כמו שהוא ירגיש בדף.',
    'artist_create.step1_title': 'פרופיל ראשוני',
    'artist_create.step1_desc': 'תמונה, שמות ותוכן פתיחה שמייצרים רושם חי, נקי ומדויק כבר מההתחלה.',
    'artist_create.profile_photo_label': 'תמונת פרופיל',
    'artist_create.profile_photo_hint': 'תמונה נקייה וברורה שתהיה הפנים של הדף.',
    'artist_create.paste_photo_url': 'הדבק כאן קישור לתמונה',
    'artist_create.name_he': 'שם בעברית',
    'artist_create.name_he_placeholder': 'שם האמן בעברית *',
    'artist_create.name_en': 'שם באנגלית',
    'artist_create.banner_label': 'תמונת פתיחה',
    'artist_create.banner_hint': 'הרקע הרחב שמופיע בראש הדף. מומלץ יחס רוחב רחב, למשל 1920x400.',
    'artist_create.banner_media_type': 'סוג מדיה לבאנר',
    'artist_create.banner_image': 'תמונה רגילה',
    'artist_create.banner_gif': 'GIF / אנימציה',
    'artist_create.paste_banner_url': 'הדבק כאן קישור לבאנר',
    'artist_create.paste_gif_url': 'הדבק כאן קישור ל-GIF או וידאו קצר',
    'artist_create.short_desc_label': 'תיאור קצר',
    'artist_create.short_desc_placeholder': 'תיאור קצר: משפט או שניים שמספרים מי אתה ומה הסאונד או הסיפור שלך.',
    'artist_create.bio_label': 'ביוגרפיה',
    'artist_create.bio_placeholder': 'ביוגרפיה: אפשר לספר כאן על הדרך, ההשפעות, היצירה והנקודות שחשוב לך שיכירו.',
    'artist_create.step2_desc': 'כאן מחברים את הדף שלך לעולם שממשיך מחוץ לאתר, בצורה ברורה ולא עמוסה.',
    'artist_create.website_sr': 'אתר אישי',
    'artist_create.website_placeholder': 'אתר אישי - https://example.com',
    'artist_create.social_kicker': 'רשתות חברתיות',
    'artist_create.social_desc': 'הקישורים שמובילים ישר לעמודים החיים והיומיומיים שלך.',
    'artist_create.music_kicker': 'פלטפורמות מוזיקה',
    'artist_create.music_desc': 'קישורים ישירים להאזנה, צפייה ומעבר מהיר למקומות החשובים.',
    'artist_create.step3_desc': 'גלריה חיה, סרטונים ותוכן קידומי מסודר בצורה קלילה ומזמינה.',
    'artist_create.gallery_kicker': 'גלריית מדיה',
    'artist_create.gallery_desc': 'אוסף תמונות שמרחיב את הסיפור הוויזואלי שלך מעבר לתמונה הראשית.',
    'artist_create.add_image': 'הוסף תמונה',
    'artist_create.add_image_hint': 'קוביה חדשה לגלריה',
    'artist_create.add_video': 'הוסף סרטון',
    'artist_create.add_video_hint': 'כחלק מהגלריה המורחבת',
    'artist_create.remove_image': 'מחיקת תמונה',
    'artist_create.gallery_img_alt': 'תמונה בגלריה',
    'artist_create.caption_placeholder': 'כיתוב קצר, אם צריך',
    'artist_create.remove_video': 'מחיקת סרטון',
    'artist_create.video_title_placeholder': 'כותרת הסרטון',
    'artist_create.paste_video_url': 'הדבק כאן קישור לסרטון',
    'artist_create.performance_kicker': 'הופעה',
    'artist_create.performance_desc': 'אם יש הופעה לקדם, אפשר להוסיף כאן בלוק בולט ועדין אחרי הגלריה.',
    'artist_create.perf_banner_label': 'באנר הופעה',
    'artist_create.perf_banner_hint': 'מומלץ להעלות תמונה רחבה שמציגה את המופע בצורה ברורה.',
    'artist_create.perf_banner_placeholder': 'הדבק כאן קישור לבאנר ההופעה',
    'artist_create.perf_ticket_placeholder': 'קישור לרכישת כרטיסים',
    'artist_create.perf_show_banner': 'להציג את באנר ההופעה בדף האמן',
    'artist_create.back_to_chat': 'חזרה לצ\'אט',
    'artist_create.prev': 'חזרה',
    'artist_create.next': 'המשך',
    'artist_create.submit': 'שליחה',
    'artist_create.platform_instagram': 'הדבק קישור לאינסטגרם',
    'artist_create.platform_facebook': 'הדבק קישור לפייסבוק',
    'artist_create.platform_tiktok': 'הדבק קישור לטיקטוק',
    'artist_create.platform_twitter': 'הדבק קישור ל-X / Twitter',
    'artist_create.platform_youtube': 'הדבק קישור ליוטיוב',
    'artist_create.platform_spotify': 'הדבק קישור לספוטיפיי',
    'artist_create.platform_zing': 'הדבק קישור לזינג',

    // Add song modal
    'song_modal.edit_title': 'עריכת שיר',
    'song_modal.add_title': 'הוספת שיר חדש',
    'song_modal.add_short': 'הוספת שיר',
    'song_modal.close_continue': 'אפשר לסגור את החלון או להמשיך משם.',
    'song_modal.which_song': 'איזה שיר תרצה להוסיף?',
    'song_modal.song_ready': 'השם והתמונה מוכנים, נמשיך למילים ולאקורדים.',
    'song_modal.change_song': 'לבחור שיר אחר',
    'song_modal.song_exists': 'השיר כבר קיים במערכת',
    'song_modal.go_to_song': 'לעבור לדף השיר',
    'song_modal.wrong_song': 'זה לא השיר שהתכוונתי',
    'song_modal.not_found_manual': 'לא מצאת ברשימה?',
    'song_modal.paste_yt_manual': 'להדביק קישור ליוטיוב ידנית',
    'song_modal.full_manual': 'הוספה ידנית מלאה',
    'song_modal.full_manual_hint': 'לעבור לטופס הישן בלי קישור ליוטיוב',
    'song_modal.paste_yt_ok': 'אין בעיה, אפשר להדביק כאן קישור ליוטיוב ונמשיך משם.',
    'song_modal.song_title_input': 'הכנס כאן שם שיר',
    'song_modal.paste_yt_link': 'הדבק כאן קישור ליוטיוב',
    'song_modal.invalid_yt': 'צריך להדביק קישור תקין ליוטיוב',
    'song_modal.paste_link_manual': 'להדביק קישור ידני',
    'song_modal.continue_no_link': 'להמשיך בלי לינק',
    'song_modal.auto_id_label': 'נבחר לזיהוי אוטומטי',
    'song_modal.add_lyrics_prompt': 'מעולה. עכשיו נשאר רק להוסיף מילים ואקורדים.',
    'song_modal.paste_lyrics': 'הדבק כאן את המילים והאקורדים של השיר...',
    'song_modal.lyrics_error': 'צריך להוסיף מילים ואקורדים כדי להמשיך',
    'song_modal.sheet_music_label': 'קובץ תווים (אופציונלי)',
    'song_modal.sheet_music_placeholder': 'קישור לקובץ תווים או העלאה',
    'song_modal.almost_done': 'הכול מוכן כמעט.',
    'song_modal.before_send': 'לפני שליחה',
    'song_modal.review_note': 'בדיקה קצרה, ואם צריך אפשר לעדכן.',
    'song_modal.song_name_label': 'שם השיר:',
    'song_modal.artist_label': 'אמן:',
    'song_modal.original_key_detected': 'סולם מקורי:',
    'song_modal.easy_key_detected': 'סולם קל:',
    'song_modal.auto_detected': '(זוהה אוטומטית)',
    'song_modal.song_image_alt': 'תמונת שיר',
    'song_modal.song_name_field': 'שם השיר *',
    'song_modal.song_title_placeholder': 'שם השיר',
    'song_modal.yt_link_field': 'קישור יוטיוב *',
    'song_modal.yt_placeholder': 'קישור יוטיוב',
    'song_modal.image_placeholder': 'קישור לתמונה',
    'song_modal.artists_field': 'אמנים *',
    'song_modal.add_artist_placeholder': 'להוסיף אמן',
    'song_modal.artist_new': 'חדש',
    'song_modal.artist_similar': 'מצאנו אמנים דומים. אפשר ללחוץ כדי להחליף.',
    'song_modal.pending_admin': 'יישלח לאישור מנהל',
    'song_modal.original_key_field': 'סולם מקורי *',
    'song_modal.select_key': 'בחר סולם',
    'song_modal.easy_key_field': 'סולם קל',
    'song_modal.select_easy_key': 'בחר סולם קל',
    'song_modal.preview_edit': 'עריכה',
    'song_modal.save_changes': 'שמירת שינויים',
    'song_modal.saving': 'שומר...',
    'song_modal.submit_approval': 'שליחה לאישור',
    'song_modal.prev': 'חזרה',
    'song_modal.next': 'הבא',
    'song_modal.preview_next': 'מעבר לתצוגה מקדימה ואישור',
    'song_modal.song_details': 'פרטי השיר:',
    'song_modal.song_name_req': 'שם השיר *',
    'song_modal.song_name_placeholder_legacy': 'הכנס שם השיר',
    'song_modal.yt_searching': 'מחפש התאמות מיוטיוב...',
    'song_modal.yt_hint': 'אפשר לבחור תוצאה ולמלא אוטומטית את הקישור, התמונה ושם האמן.',
    'song_modal.yt_result_alt': 'תוצאת YouTube',
    'song_modal.yt_autofill': 'מלא אוטומטית',
    'song_modal.yt_autofilled': 'נבחר סרטון מיוטיוב והפרטים הבסיסיים מולאו אוטומטית.',
    'song_modal.yt_artist_suggested': 'אמן משוער:',
    'song_modal.duplicate_warning': '⚠️ נמצאו שירים דומים:',
    'song_modal.title_error': 'שם השיר הוא שדה חובה (2-120 תווים)',
    'song_modal.artists_label_legacy': 'אמנים (עד 5) *',
    'song_modal.add_artist_legacy': 'הוסף אמן...',
    'song_modal.similar_artists_prefix': 'מצאנו אמנים דומים ל',
    'song_modal.similar_artists_q': 'לבחור אחד מהם?',
    'song_modal.no_match_prefix': 'לא מצאנו התאמה בטוחה ל',
    'song_modal.no_match_new': 'אפשר להוסיף אותו כאמן חדש.',
    'song_modal.new_artist': 'זה אמן חדש',
    'song_modal.add_as_new': 'הוסף כאמן חדש',
    'song_modal.add_new_artist_prefix': 'הוסף אמן חדש: ',
    'song_modal.pending_admin_warning': '⚠️ יישלח לאישור מנהל',
    'song_modal.artists_error': 'חובה להוסיף לפחות אמן אחד',
    'song_modal.composer_label': 'מלחין',
    'song_modal.add_composer': 'הוסף מלחין (אופציונלי)...',
    'song_modal.add_new_composer_prefix': 'הוסף מלחין חדש: ',
    'song_modal.pending_admin_review': '⚠️ יישלח לבדיקת מנהל',
    'song_modal.yt_link_label': 'קישור YouTube *',
    'song_modal.spotify_label': 'קישור Spotify',
    'song_modal.paste_image': 'הדבק קישור לתמונה',
    'song_modal.tags_label': 'תגיות',
    'song_modal.add_tag': 'הוסף תגית...',
    'song_modal.add_new_tag_prefix': 'הוסף תגית חדשה: ',
    'song_modal.genres_label': 'ז\'אנרים',
    'song_modal.add_genre': 'הוסף ז\'אנר...',
    'song_modal.add_new_genre_prefix': 'הוסף ז\'אנר חדש: ',
    'song_modal.content_header': 'מילים ואקורדים',
    'song_modal.lyrics_placeholder_legacy': 'כתוב כאן את המילים והאקורדים *',
    'song_modal.lyrics_error_legacy': 'שדה חובה (מינימום 10 תווים)',
    'song_modal.auto_detect': 'זיהוי אוטומטי',
    'song_modal.auto_detected_key': 'זוהה אוטומטית:',
    'song_modal.key_error': 'יש לבחור סולם מקורי',
    'song_modal.easy_key_label': 'סולם קל לנגינה',
    'song_modal.preview_title': 'תצוגה מקדימה',
    'song_modal.preview_check_edit': 'בדקו את השינויים לפני השמירה',
    'song_modal.preview_check_new': 'בדקו את הפרטים לפני שנעלה',
    'song_modal.tag_for_profile': 'שיוך התוכן לפרופיל ציבורי',
    'song_modal.tag_myself': 'האם לתייג את התוכן על שמך',
    'song_modal.tag_myself_yes': 'כן, לתייג על שמי',
    'song_modal.filter_all': 'כולם',
    'song_modal.filter_teachers': 'מורים',
    'song_modal.filter_providers': 'נותני שירות',
    'song_modal.filter_artists': 'אמנים',
    'song_modal.filter_users': 'חברים רגילים',
    'song_modal.sort_name': 'מיון לפי שם',
    'song_modal.sort_type': 'מיון לפי סוג',
    'song_modal.search_profile': 'חפש לפי שם אמן / מורה / בעל מקצוע...',
    'song_modal.no_results': 'לא נמצאו תוצאות',
    'song_modal.approved_label': 'מאושר לפרסום (מנהל בלבד)',
    'song_modal.back': 'חזור',
    'song_modal.cancel': 'ביטול',
    'song_modal.send_approval': 'שלח לאישור',
    'song_modal.save_edit': 'שמור שינויים',
    'song_modal.publish_song': 'פרסם שיר',
    'song_modal.success_updated': 'השיר עודכן בהצלחה',
    'song_modal.success_sent': 'נשלח לבדיקת מנהל',
    'song_modal.error_update': 'אירעה שגיאה בעדכון השיר',
    'song_modal.error_save': 'אירעה שגיאה בשמירת השיר',
    'song_modal.smart_step1_title': 'מתחילים מבחירת השיר',
    'song_modal.smart_step2_title': 'מוסיפים מילים ואקורדים',
    'song_modal.smart_step3_title': 'בודקים לפני שליחה',
    'song_modal.smart_step1_desc': 'כותבים שם שיר או מדביקים קישור, ואני מסדר את הפתיחה.',
    'song_modal.smart_step2_desc': 'מדביקים את התוכן, ואני מזהה סולם ומכין תצוגה.',
    'song_modal.smart_step3_desc': 'עוברים על הפרטים פעם אחרונה ושולחים.',
    'song_modal.helper_wrong_song': 'אם זה לא השיר הנכון, אפשר לבחור שיר אחר.',
    'song_modal.helper_searching_yt': 'מחפש עכשיו תוצאות ביוטיוב...',
    'song_modal.helper_loading_meta': 'שולף עכשיו את התמונה והפרטים מהקישור.',
    'song_modal.helper_no_results': 'לא נמצאה התאמה טובה. אפשר לנסות ניסוח אחר או לבחור בהדבקת קישור ידנית.',
    'song_modal.helper_detecting_key': 'מזהה עכשיו סולם מקורי וסולם קל.',
    'song_modal.preview_ready': 'הכול כמעט מוכן. בודקים את הפרטים ושולחים לאישור.',
    'song_modal.preview_ready_pre': 'הכול כמעט מוכן. בודקים את',
    'song_modal.preview_ready_suf': 'ושולחים לאישור.',
    'song_modal.action_preview': 'בדיקה ותצוגה',
    'song_modal.profile_artist': 'אמן',
    'song_modal.profile_user': 'חבר רגיל',
    'song_modal.profile_teacher': 'מורה',
    'song_modal.profile_service': 'נותן שירות',
    'song_modal.profile_pro': 'מורה / בעל מקצוע',
    'song_modal.not_linked': ' · לא מקושר לחשבון',
    'song_modal.success_add': 'נשלח לאישור מנהל. תודה.',
    'song_modal.error_prefix': 'שגיאה',
  },
  en: {
    'nav.home': 'Home',
    'nav.chords': 'Chords',
    'nav.news': 'Music News',
    'nav.index_full': 'Music World Index',
    'nav.index_short': 'Index',
    'user.admin': 'Admin',
    'user.profile': 'My Profile',
    'user.playlists': 'My Playlists',
    'user.logout': 'Sign Out',
    'user.login': 'Sign In',
    'notif.loading': 'Loading notifications...',
    'notif.empty': 'No new notifications.',
    'notif.all': 'All Notifications',
    'notif.close': 'Close',
    'notif.center_empty': 'No notifications.',
    'notif.clear_history': 'Clear History',
    'notif.marketing': 'Promotional',
    'notif.media': 'Attached Media',
    'notif.attachment': 'Attachment',
    'notif.error': 'Failed to load notifications.',
    'notif.general_report_title': 'General system message',
    'footer.home': 'Home',
    'footer.chords': 'Chords',
    'footer.index': 'Index',
    'footer.music_news': 'Music News',
    'footer.artists': 'Artists',
    'footer.events': 'Shows',
    'footer.articles': 'Articles',
    'footer.playlists': 'Playlist Library',
    'footer.chord_dict': 'Chord Dictionary',
    'footer.random_song': 'Random Song',
    'footer.tuner': 'Guitar & Ukulele Tuner',
    'footer.newsletter_title': 'Stay Updated',
    'footer.newsletter_sub': 'Songs, artists and articles straight to your inbox',
    'footer.newsletter_placeholder': 'Email address',
    'footer.newsletter_btn': 'Subscribe',
    'footer.acum': 'This site operates under an ACUM license',
    'footer.copyright': '© Acordiskate. All rights reserved.',
    'footer.rights_notice': 'This site respects copyright — if your rights were infringed,',
    'footer.rights_resolve': 'to resolve the matter',
    'footer.advertising': 'For advertising and partnerships —',
    'footer.contact': 'contact us',

    // Song page
    'song.chords_subtitle': 'Song Chords',
    'song.lyrics': 'Lyrics:',
    'song.music': 'Music:',
    'song.add_to_playlist': 'Add to Playlist',
    'song.share': 'Share',
    'song.print': 'Print',
    'song.report_error': 'Report Error',
    'song.key_prefix': 'Key:',
    'song.easy_version': 'Easy Mode',
    'song.auto_scroll': 'Auto Scroll',
    'song.chord_diagrams_title': 'Song Chord Diagrams',
    'song.chord_diagrams_sub': 'All chords in this song for your selected instrument.',
    'song.capo_prefix': 'Capo fret',
    'song.capo_suffix': 'to play in the original key',
    'song.rate_title': 'Rate This Song',
    'song.rating_1': '1 star — Poor',
    'song.rating_2': '2 stars — Not Good',
    'song.rating_3': '3 stars — OK',
    'song.rating_4': '4 stars — Good',
    'song.rating_5': '5 stars — Excellent',
    'song.rating_poor': 'Poor',
    'song.rating_not_good': 'Not Good',
    'song.rating_ok': 'OK',
    'song.rating_good': 'Good',
    'song.rating_excellent': 'Excellent!',
    'song.login_to_rate': 'Log in to rate',
    'song.has_sheet_music': 'This song has sheet music',
    'song.go_to_sheet_music': 'View Sheet Music',
    'song.need_help_teacher': 'Need help playing? Our teachers are here for you',
    'song.find_teacher': 'Find a Teacher',
    'song.more_by_artist': 'More chords by',
    'song.loading': 'Loading...',
    'song.loading_song': 'Loading song...',
    'song.try_again': 'Try Again',
    'song.you_might_like': 'You Might Also Like',
    'song.popular_this_week': 'Most Viewed This Week',
    'song.no_more_songs': 'No more songs to show',
    'song.uploaded_by': 'Uploaded by',
    'song.open_youtube': 'Open on YouTube',
    'song.open_pdf': 'Open PDF',
    'song.open_full': 'Open Full File',
    'song.link_copied': 'Link Copied!',
    'song.known_all': 'You know all the chords in this song',
    'song.missing_chords': "You're missing",
    'song.missing_chords_suffix': 'chords',
    'song.to_play_song': 'to play this song with your selected chords',
    'song.need_to_learn': 'Need to learn:',
    'song.close': 'Close',
    'song.instr_piano': 'Piano',
    'song.instr_guitar': 'Guitar',
    'song.instr_ukulele': 'Ukulele',
    'song.instr_lyrics': 'Lyrics only',
    'song.transpose_down': 'Transpose down half step',
    'song.transpose_up': 'Transpose up half step',
    'song.transpose_reset': 'Reset transpose',
    'song.font_decrease': 'Decrease text',
    'song.font_increase': 'Increase text',
    'song.scroll_slow': 'Slow down',
    'song.scroll_fast': 'Speed up',
    'song.scroll_stop': 'Stop',
    'song.day_mode': 'Day mode',
    'song.night_mode': 'Night mode',
    'song.show_diagrams': 'Show chord diagrams',
    'song.sheet_music_alt': 'Sheet music for song',
    'song.known_chords_info': 'This info is calculated based on the chords you marked as known. It shows how many chords you are missing to play the song.',

    // Chords page
    'chords.title': 'Chords',
    'chords.subtitle': 'The largest and first chord library in Jewish music',
    'chords.search_placeholder': 'Search for a song, artist or lyrics...',
    'chords.sort_newest': 'Newest → Oldest',
    'chords.sort_most_viewed': 'Most Viewed',
    'chords.sort_az': 'A–Z',
    'chords.songs_i_can_play': 'Songs I Can Play',
    'chords.chord_dictionary': 'Chord Dictionary',
    'chords.tuner': 'Guitar & Ukulele Tuner',
    'chords.random_song': 'Random Song',
    'chords.known_filter_title': 'Songs close to what I can play',
    'chords.known_filter_sub': 'Calculated based on the chords you marked vs. the chords in each song. Add chords via the + button in a chord diagram or through your profile.',
    'chords.sort_exact': 'Exactly what I can play',
    'chords.sort_closest': 'Closest to what I know',
    'chords.sort_popular': 'Popular',
    'chords.clear_filters': 'Clear Filters',
    'chords.results_prefix': 'Found',
    'chords.results_suffix': 'results',
    'chords.loading': 'Loading...',
    'chords.no_results': 'No Results Found',
    'chords.prev': 'Previous',
    'chords.next': 'Next',
    'chords.section_recent': 'Recently Added',
    'chords.section_popular': 'Trending Now',
    'chords.section_most_viewed': 'Most Viewed',
    'chords.section_dont_miss': "Don't Miss",
    'chords.section_recently_viewed': 'Recently Viewed',
    'chords.section_all': 'All Chords',

    // Profile page
    'profile.title': 'My Profile',
    'profile.subtitle': 'Personal details for account management — not shown on your public profile',
    'profile.level': 'Level',
    'profile.completion_title': 'A few more details to complete your profile',
    'profile.completion_sub': 'So we can show you more accurate results',
    'profile.completion_cta': 'Complete your details >',
    'profile.no_page': "You don't have a page yet",
    'profile.add_page': 'Add a Page +',
    'profile.manage_page_title': 'Manage Your Page',
    'profile.manage_page_sub': 'The page shown to site members',
    'profile.edit_page': 'Edit Page',
    'profile.view_page': 'View Page',
    'profile.page_type': 'Page type:',
    'profile.status': 'Status:',
    'profile.saving': 'Saving...',
    'profile.disable_page': 'Disable Page',
    'profile.enable_page': 'Enable Page',
    'profile.change_account_type': 'Change Account Type >',
    'profile.subscriptions_title': 'Subscriptions & Payments',
    'profile.subscriptions_sub': 'Manage your subscriptions and payment history',
    'profile.upgrade': 'Upgrade Plan',
    'profile.manage': 'Manage',
    'profile.account': 'Account:',
    'profile.known_chords_title': 'Chords I Can Play:',
    'profile.adding': 'Adding...',
    'profile.basics_added': 'Basics Added',
    'profile.add_basics': 'Add Basic Chords',
    'profile.removing': 'Removing...',
    'profile.remove_all': 'Remove All',
    'profile.no_chords': 'No chords marked yet',
    'profile.my_content_title': 'My Content:',
    'profile.content_chords': 'Chords',
    'profile.content_articles': 'Articles & Blog',
    'profile.content_events': 'Shows',
    'profile.pending': 'Pending Approval',
    'profile.no_songs': 'No chords uploaded yet',
    'profile.no_articles': 'No articles or blog posts yet',
    'profile.no_events': 'No shows uploaded yet',
    'profile.show_more': 'Show More',
    'profile.go_to_playlists': 'Go to Saved Lists',
    'profile.modal_title': 'Complete Personal Details',
    'profile.modal_sub': "Details won't appear on your public profile",
    'profile.label_email': 'Email',
    'profile.label_phone': 'Phone',
    'profile.label_address': 'Address',
    'profile.label_birthdate': 'Date of Birth',
    'profile.address_placeholder': 'City, street and number',
    'profile.save': 'Save',
    'profile.instrument_guitar': 'Guitar',
    'profile.instrument_piano': 'Piano',
    'profile.instrument_ukulele': 'Ukulele',
    'profile.level_0': 'Registered User',
    'profile.level_1': 'Beginner',
    'profile.level_2': 'Contributor',
    'profile.level_3': 'Top Contributor',
    'profile.sub_free': 'Free',
    'profile.sub_active': 'Active',
    'profile.sub_trial': 'Free Trial',
    'profile.sub_pending': 'Pending Payment',
    'profile.sub_cancelled': 'Cancelled',
    'profile.sub_expired': 'Expired',
    'profile.sub_suspended': 'Suspended',
    'profile.sub_inactive': 'Inactive',
    'profile.page_active': 'Page Active',
    'profile.page_pending_approval': 'Pending Approval',
    'profile.page_off': 'Page Off',
    'profile.page_type_artist': 'Artist',
    'profile.page_type_teacher': 'Music Teacher',
    'profile.page_type_provider': 'Professional',
    'profile.page_type_user': 'Regular User',
    'profile.type_blog': 'Blog',
    'profile.type_article': 'Article',
    'profile.confirm_remove_all': 'Remove all marked chords for',
    'profile.disconnecting': 'Disconnecting...',

    // FAB / Quick-Add Assistant
    'fab.root_question': 'What would you like to add to the site?',
    'fab.root_helper': 'Adding content earns you a special badge and exclusive options for advanced members.',
    'fab.content_question': 'Great, what content would you like to add?',
    'fab.index_question': 'Got it, what profile would you like to index?',
    'fab.artist_question': 'How would you like to add the artist?',
    'fab.song_selected': 'Great, let\'s proceed to add chords.',
    'fab.chord_request_question': 'Which song would you like us to add chords for?',
    'fab.opt_chords': 'Chords',
    'fab.opt_content': 'Content',
    'fab.opt_event': 'Show',
    'fab.opt_index': 'Index a Profile',
    'fab.opt_artist': 'Artist',
    'fab.opt_chord_request': 'Request Chords for a Song',
    'fab.opt_contact_form': 'Contact Us',
    'fab.opt_report': 'Report',
    'fab.opt_news': 'Music News',
    'fab.opt_blog': 'Other Content',
    'fab.opt_teacher': 'Music Teacher',
    'fab.opt_other': 'Other',
    'fab.opt_artist_account': 'Convert to Artist Account',
    'fab.opt_artist_community': 'Add Artist without Account',
    'fab.secondary_label': 'Or you might want',
    'fab.back': 'Back',
    'fab.submitting': 'Submitting...',
    'fab.submit_approval': 'Submit for Approval',
    'fab.submit_request': 'Send Request',
    'fab.submit_contact': 'Send',
    'fab.close': 'Close',
    'fab.uploading': 'Uploading...',
    'fab.upload_image': 'Upload Image',
    'fab.image_link': 'Image Link',
    'fab.use_video_thumb': 'Use Video Thumbnail',
    'fab.optional_label': 'A few more details (optional)',
    'fab.optional_hint': 'Optional',
    'fab.article_title': 'Title',
    'fab.article_content': 'Content',
    'fab.article_subtitle': 'Subtitle',
    'fab.author_name': 'Author Name',
    'fab.short_desc': 'Short Description',
    'fab.video_youtube': 'YouTube Video',
    'fab.video_note': 'You can attach a video link',
    'fab.image': 'Image',
    'fab.image_note_article': 'Upload, paste a link, or use the video thumbnail',
    'fab.image_note_event': 'Upload an image or paste a link',
    'fab.tag_content': 'Assign Content to Uploader',
    'fab.tag_myself': 'Tag content under your name',
    'fab.tag_myself_yes': 'Yes, tag under my name',
    'fab.filter_all': 'All',
    'fab.filter_teachers': 'Teachers',
    'fab.filter_providers': 'Service Providers',
    'fab.filter_artists': 'Artists',
    'fab.filter_users': 'Regular Members',
    'fab.sort_name': 'Sort by Name',
    'fab.sort_type': 'Sort by Type',
    'fab.search_profile': 'Search by name in selected list',
    'fab.search_artist': 'Search for an artist to tag',
    'fab.no_results': 'No results found',
    'fab.no_artists': 'No artists found',
    'fab.not_linked': ' · Not linked to account',
    'fab.profile_type_artist': 'Artist',
    'fab.profile_type_user': 'Regular Member',
    'fab.profile_type_teacher': 'Teacher',
    'fab.profile_type_provider': 'Service Provider',
    'fab.profile_type_general': 'Teacher / Service Provider',
    'fab.event_ticket_link': 'Ticket Link',
    'fab.event_date': 'Date',
    'fab.event_tag_artist': 'Tag an Artist from the Site',
    'fab.event_artist_type': 'Artist',
    'fab.event_name': 'Show Name',
    'fab.event_artist_name': 'Artist Name',
    'fab.event_location': 'Location',
    'fab.event_price': 'Price',
    'fab.event_description': 'Short Description',
    'fab.chord_song_name': 'Song Name',
    'fab.chord_artist_name': 'Artist Name',
    'fab.contact_full_name': 'Full Name',
    'fab.contact_email': 'Email',
    'fab.contact_subject': 'Subject',
    'fab.contact_select_subject': 'Select a subject',
    'fab.contact_subject_general': 'General Question',
    'fab.contact_subject_tech': 'Technical Issue',
    'fab.contact_subject_partner': 'Partnership',
    'fab.contact_subject_improve': 'Suggestion',
    'fab.contact_subject_other': 'Other',
    'fab.contact_message': 'Message',
    'fab.contact_message_placeholder': 'Write your message here...',
    'fab.contact_attachments': 'Attachments',
    'fab.contact_attach_file': 'Attach File',
    'fab.success_song': 'Song submitted for admin approval.',
    'fab.success_news': 'News submitted for admin approval.',
    'fab.success_article': 'Content submitted for admin approval.',
    'fab.success_event': 'Show submitted for admin approval.',
    'fab.success_chord_request': 'Request sent! We\'ll do our best to add the chords soon.',
    'fab.success_contact': 'Message sent! We\'ll get back to you shortly.',

    // Shared UI
    'shared.ended': 'Ended',
    'shared.tickets': 'Get Tickets',
    'shared.loading': 'Loading...',
    'shared.try_again': 'Try Again',
    'shared.show_more': 'Show More',
    'shared.cancel': 'Cancel',
    'shared.save': 'Save',
    'shared.close': 'Close',
    'shared.songs_suffix': 'songs',
    'shared.prev': 'Previous',
    'shared.next': 'Next',
    'shared.search': 'Search',
    'shared.reset': 'Reset',
    'shared.saving': 'Saving...',

    // Song card
    'song_card.label': 'Song Chords',
    'song_card.unknown_artist': 'Unknown Artist',
    'song_card.all_known': 'All chords known',
    'song_card.missing_one': 'Missing 1 chord',
    'song_card.missing_prefix': 'Missing',
    'song_card.missing_suffix': 'chords',
    'song_card.info_all': 'Based on your known chords, you know all the chords in this song.',
    'song_card.info_missing_prefix': 'Based on your known chords, you\'re missing',
    'song_card.info_missing_suffix': 'chords to play this song.',

    // Report modal
    'report.title': 'Report an Issue',
    'report.sent': 'Report Sent!',
    'report.thanks': 'Thank you, we\'ll handle it soon',
    'report.what_problem': 'What\'s the problem?',
    'report.detail': 'Details',
    'report.placeholder': 'Briefly describe the issue...',
    'report.sending': 'Sending...',
    'report.submit': 'Submit',
    'report.type_error': 'Content Error',
    'report.type_inappropriate': 'Inappropriate Content',
    'report.type_other': 'Other',
    'report.validation': 'Please describe the issue in at least 10 characters',
    'report.error_submit': 'Error submitting report',

    // Pagination
    'paginate.showing': 'Showing',
    'paginate.of': 'of',
    'paginate.first_page': 'First Page',
    'paginate.prev_page': 'Previous Page',
    'paginate.next_page': 'Next Page',
    'paginate.last_page': 'Last Page',

    // Auth modal
    'auth.login_title': 'Sign In:',
    'auth.register_title': 'Sign Up:',
    'auth.username': 'Username',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.google_login': 'Sign In with Google',
    'auth.google_register': 'Sign Up with Google',
    'auth.terms': 'By registering I agree to the site terms and consent to receive updates and marketing content by email.',
    'auth.terms_link': 'Site Terms',
    'auth.submit_login': 'Sign In ←',
    'auth.submit_register': 'Continue ←',
    'auth.no_account': 'Don\'t have an account?',
    'auth.register_link': 'Sign Up',
    'auth.has_account': 'Already have an account?',
    'auth.login_link': 'Sign In',
    'auth.password_hint': '8+ chars, uppercase, digit and special char (@$!%*?&#)',

    // Forgot password
    'forgot.title_request': 'Password Recovery',
    'forgot.title_verify': 'Set New Password',
    'forgot.subtitle_request': 'We\'ll send you a verification code to reset your password',
    'forgot.subtitle_verify': 'Enter the code you received and a new password',
    'forgot.username_label': 'Username or Email',
    'forgot.username_placeholder': 'Username or email address',
    'forgot.recovery_method': 'Recovery Method',
    'forgot.send_code': 'Send Verification Code',
    'forgot.code_label': 'Verification Code',
    'forgot.code_placeholder': 'Enter the code you received',
    'forgot.new_password': 'New Password',
    'forgot.requirements_title': 'Password must include:',
    'forgot.strength_weak': 'Weak',
    'forgot.strength_medium': 'Medium',
    'forgot.strength_strong': 'Strong',
    'forgot.confirm_password': 'Confirm Password',
    'forgot.reset': 'Reset Password',

    // Additional details modal
    'details.step1_title': 'A few details to complete your experience',
    'details.step1_sub': 'Do you play an instrument?',
    'details.piano': 'Keys',
    'details.guitar': 'Guitar',
    'details.other_instrument': 'Other',
    'details.no_instrument': 'I don\'t play',
    'details.beginner': 'Beginner',
    'details.intermediate': 'Intermediate',
    'details.professional': 'Professional',
    'details.continue': 'Continue <',
    'details.skip': 'Skip to site',
    'details.step2_title': 'How would you like to use Acordiskate?',
    'details.step2_sub': 'You can change this later',
    'details.regular_user': 'Regular User',
    'details.regular_desc': 'Discover music, play, learn and enjoy',
    'details.professional_user': 'Professional',
    'details.professional_desc': 'Offer music services and appear in the index',
    'details.teacher_user': 'Teacher',
    'details.teacher_desc': 'Offer lessons and appear in the teachers index',
    'details.artist_user': 'Artist',
    'details.artist_desc': 'Share content and manage your artist page',

    // Home page
    'home.subtitle': 'The home of Jewish music.',
    'home.search_placeholder': 'Search for songs, chords, lyrics, teachers, or anything',
    'home.search_songs': 'Songs & Chords',
    'home.search_artists': 'Artists',
    'home.search_articles': 'Articles',
    'home.search_teachers': 'Teachers',
    'home.search_professionals': 'Professionals',
    'home.search_playlists': 'Saved Playlists',
    'home.search_by_lyrics': 'Songs by Lyrics',
    'home.search_deep_label': 'Deep Search',
    'home.searching_deep': 'Searching lyrics...',
    'home.no_results': 'No results found for',
    'home.quick_dict': 'Chord Dictionary ›',
    'home.quick_tuner': 'Guitar & Ukulele Tuner ›',
    'home.quick_artists': 'Artists List ›',
    'home.news_title': 'Music News',
    'home.news_link': 'All News ‹',
    'home.promo_chords_title': 'Chords',
    'home.promo_chords_sub': 'The largest and first chord library in Jewish music',
    'home.promo_chords_link': 'All Chords ‹',
    'home.promo_chords_random': 'Random Song',
    'home.recent_chords': 'Recently Added Chords',
    'home.popular_chords': 'Popular Chords',
    'home.popular_artists': 'Popular Artists',
    'home.artists_link': 'All Artists ‹',
    'home.teachers_title': 'System Picks',
    'home.teachers_link': 'To the Music Index',
    'home.default_teacher': 'Music Teacher',
    'home.promo_index_title': 'Music World Index',
    'home.promo_index_sub': 'The largest database of music service providers',
    'home.promo_index_link': 'To Index ‹',
    'home.promo_index_join': 'Join the Index ‹',
    'home.professionals_title': 'Professionals',
    'home.professionals_link': 'All Professionals ‹',
    'home.default_pro': 'Professional',
    'home.featured_title': 'System Picks',
    'home.upcoming_events': 'Upcoming Shows',
    'home.events_link': 'All Shows ‹',
    'home.content_title': 'Content',
    'home.content_link': 'All Content ‹',

    // Notifications page
    'notif_page.eyebrow': 'Notification Center',
    'notif_page.title': 'All your updates in one place',
    'notif_page.desc': 'Approvals, status updates and personal messages from the system will appear here.',
    'notif_page.delete_all': 'Delete All History',
    'notif_page.loading': 'Loading notifications...',
    'notif_page.empty_title': 'No Notifications',
    'notif_page.empty_desc': 'When there\'s a new update, it will appear here.',
    'notif_page.marketing_tag': 'Promotional',
    'notif_page.open_file': 'Open Attached File',
    'notif_page.view': 'View Update',
    'notif_page.delete_btn': 'Delete Notification',
    'notif_page.error': 'Failed to load notifications.',
    'notif_page.attach_default': 'Attachment',

    // Artists list
    'artists.label': 'Artists',
    'artists.title': 'Our Artists',
    'artists.site_count': 'artists on site',
    'artists.search_placeholder': 'Search artist...',
    'artists.sort_az': 'A–Z',
    'artists.sort_popular': 'Popular',
    'artists.sort_new': 'New',
    'artists.songs_suffix': 'songs',
    'artists.empty': 'No Artists Found',
    'artists.empty_search': 'Try a different search term',

    // Events page
    'events.title': 'Shows',
    'events.filter_upcoming': 'Upcoming',
    'events.filter_all': 'All',
    'events.filter_past': 'Past',
    'events.empty': 'No Shows to Display',
    'events.tickets': 'Get Tickets',
    'events.tab_news': 'News',
    'events.tab_blog': 'Blog',
    'events.tab_events': 'Shows',

    // Music news / Blog
    'news.load_failed': 'Failed to load news. Please check your connection and try again.',
    'news.no_content': 'No news to display right now.',
    'blog.load_failed': 'Failed to load blog. Please check your connection and try again.',
    'blog.no_content': 'No blog posts to display right now.',

    // Playlists page
    'playlists.title': 'My Playlists',
    'playlists.subtitle': 'One place for all your saves — songs, chords, articles and personal lists.',
    'playlists.community_desc': 'Discover lists shared by other users with the community',
    'playlists.community_btn': 'Community Playlist Library',
    'playlists.new_name_placeholder': 'New list name',
    'playlists.public': 'Public List',
    'playlists.private': 'Private List',
    'playlists.create': 'Create List',
    'playlists.new_btn': 'New List',
    'playlists.options': 'Options',
    'playlists.export_book': 'Export as Chord Book',
    'playlists.duplicate': 'Duplicate List',
    'playlists.delete': 'Delete List',
    'playlists.empty': 'No lists yet',
    'playlists.saved_title': 'My Saved Items',
    'playlists.articles_title': 'Articles & Content',
    'playlists.saved_songs': 'Saved Songs',
    'playlists.remove_saved': 'Remove from Saved',
    'playlists.empty_all_title': 'No saves yet',
    'playlists.empty_all_text': 'Save songs, articles and general content and they\'ll appear here.',
    'playlists.image_placeholder': 'Paste image URL',
    'playlists.songs_count': 'songs',
    'playlists.error_load': 'Error loading playlists',
    'playlists.error_name': 'Please enter a list name',
    'playlists.error_create': 'Error creating list',
    'playlists.confirm_delete': 'Delete this list?',
    'playlists.loading': 'Loading...',

    // Playlist detail
    'playlist.back': 'Back to Lists',
    'playlist.default_badge': 'Default',
    'playlist.public': 'Public',
    'playlist.private': 'Private',
    'playlist.public_hint': 'List is visible to all site users',
    'playlist.private_hint': 'List is visible only to you',
    'playlist.chord_book_title': 'Turn this list into a Chord Book',
    'playlist.chord_book_desc': 'All songs in chord view, ready to print',
    'playlist.name_placeholder': 'List name',
    'playlist.desc_placeholder': 'Description (optional)',
    'playlist.image_placeholder': 'Paste image URL',
    'playlist.empty': 'List is Empty',
    'playlist.empty_desc': 'Add songs from the song page',
    'playlist.col_song': 'Song',
    'playlist.col_artist': 'Artist',
    'playlist.col_added': 'Added',
    'playlist.remove': 'Remove',
    'playlist.loading': 'Loading list...',
    'playlist.error_load': 'Error loading list',
    'playlist.confirm_remove': 'Remove this song from the list?',
    'playlist.confirm_delete': 'Permanently delete this list?',

    // Playlist popup
    'popup.title': 'Manage Save',
    'popup.new_list': 'New List',
    'popup.name_placeholder': 'New list name',
    'popup.public': 'Public List',
    'popup.private': 'Private List',
    'popup.create': 'Create List',
    'popup.default_playlist': 'My Saved',
    'popup.songs_suffix': 'songs',
    'popup.community': 'Playlist Library',
    'popup.my_playlists': 'My Lists',
    'popup.done': 'Done',
    'popup.error_load': 'Error loading playlists',
    'popup.error_state': 'Error loading save state',
    'popup.saved_default': 'Song saved to My Saved',
    'popup.already_saved': 'Song already in My Saved',
    'popup.error_save': 'Error saving song',
    'popup.error_remove': 'Cannot remove the song',
    'popup.error_add': 'Cannot save the song',
    'popup.error_playlist_add': 'Cannot add song to list',
    'popup.error_playlist_remove': 'Cannot remove song from list',
    'popup.error_name': 'Please enter a list name',
    'popup.error_create': 'Error creating list',
    'popup.created_ok': 'List created successfully',
    'popup.error_song_added': 'List created but could not add the song',

    // Chord dictionary
    'dict.all_roots': 'All Roots',
    'dict.all_types': 'All Types',
    'dict.title_guitar': 'Guitar Chord Dictionary',
    'dict.title_piano': 'Keyboard Chord Dictionary',
    'dict.title_ukulele': 'Ukulele Chord Dictionary',
    'dict.no_bass_chords': 'No slash chords with this bass note exist in the database',
    'dict.no_chord_prefix': 'No chord found',
    'dict.no_chord_suffix': 'in the database for the current instrument',
    'dict.instr_guitar': 'Guitar',
    'dict.instr_piano': 'Keys',
    'dict.instr_ukulele': 'Ukulele',
    'dict.playing': 'Playing...',
    'dict.play_chord': 'Play Chord',
    'dict.known_yes': 'In my known chords',
    'dict.known_no': 'Add to known chords',
    'dict.title_known': 'This chord is in your known chords list',
    'dict.title_unknown': 'Add to your known chords list',
    'dict.fingers_title': 'Finger Numbering',
    'dict.finger_1': 'Index',
    'dict.finger_2': 'Middle',
    'dict.finger_3': 'Ring',
    'dict.finger_4': 'Pinky',
    'dict.placement_title': 'Finger Placement',
    'dict.piano_press': 'Press all highlighted keys simultaneously.',
    'dict.keys_title': 'Keys to Play',
    'dict.title_filter': 'Keys',
    'dict.notes_pre': 'The chord',
    'dict.notes_mid': 'as shown here contains the notes:',
    'dict.root_pre': 'The root note is',
    'dict.scale_pre': 'The scale this chord comes from is',
    'dict.scale_and': ', and the scale degrees are:',
    'dict.guitar_placement_pre': 'To play chord',
    'dict.guitar_placement_mid': 'as shown above, place your fingers as follows:',

    // Tuner page
    'tuner.hero_guitar': 'Guitar Tuner',
    'tuner.hero_ukulele': 'Ukulele Tuner',
    'tuner.sub': 'Tune by ear and with microphone',
    'tuner.guitar': 'Guitar',
    'tuner.ukulele': 'Ukulele',
    'tuner.instructions_ear': 'Tune by ear:',
    'tuner.instructions_text': 'Click a string name to hear the correct note, then tune your instrument by turning the tuning keys until it matches.',
    'tuner.guitar_ear_note': 'Guitar tuning requires basic musical hearing ability.',
    'tuner.connecting': 'Connecting...',
    'tuner.stop_mic': 'Stop Mic',
    'tuner.start_mic': 'Tune with Mic',
    'tuner.tuning_string': 'Tuning string',
    'tuner.pick_string': 'Pick a string below and play it',
    'tuner.listening': 'Listening...',
    'tuner.in_tune': 'In Tune ✓',
    'tuner.guide_title_guitar': 'Standard Guitar Tuning',
    'tuner.guide_title_ukulele': 'Standard Ukulele Tuning',
    'tuner.guide_hint': 'Tune each string until it matches the note from this tool.',
    'tuner.guitar_guide': 'String 6 is the thickest (E2), string 1 is the thinnest (E4).',
    'tuner.ukulele_guide': 'String 4 is the thickest (G4), string 1 is the thinnest (A4).',

    // Teachers page
    'teachers.upgrade_btn': 'Become a Teacher',
    'teachers.search_placeholder': 'Search by teacher name or instrument...',
    'teachers.all_cities': 'All Cities',
    'teachers.all_instruments': 'All Instruments',
    'teachers.all_audiences': 'All Target Audiences',
    'teachers.all_languages': 'All Teaching Languages',
    'teachers.clear_filters': 'Clear Filters',
    'teachers.loading': 'Loading teachers...',
    'teachers.results_count': 'teachers',
    'teachers.no_match': 'No teachers match your search',
    'teachers.try_filter': 'Try changing the filter',
    'teachers.featured': 'Featured Teachers',
    'teachers.organ': 'Organ Teachers',
    'teachers.sound': 'Sound Teachers',
    'teachers.vocal': 'Vocal Development Teachers',
    'teachers.more': 'More',
    'teachers.additional': 'More Teachers',
    'teachers.experience_suffix': 'years experience',
    'teachers.no_teachers': 'No teachers available right now',
    'teachers.try_later': 'Try again later',
    'teachers.for_instrument': 'Teachers for',

    // Teacher detail page
    'teacher.featured_badge': 'Recommended',
    'teacher.contact': 'Contact',
    'teacher.gallery': 'Gallery',
    'teacher.testimonials': 'Student Testimonials',
    'teacher.content_title': 'My Content',
    'teacher.chords': 'Chords',
    'teacher.articles': 'Articles & Content',
    'teacher.student': 'Student',
    'teacher.loading': 'Loading teacher profile...',
    'teacher.whatsapp_label': 'Quick Message',
    'teacher.testimonial_n': 'Testimonial',
    'teacher.testimonials_next': 'More testimonials',
    'teacher.testimonials_prev': 'Previous testimonials',
    'teacher.role_prefix': 'Teacher for ',
    'teacher.role_generic': 'Music Teacher',
    'teacher.experience_prefix': 'Over ',
    'teacher.experience_suffix': 'years experience',
    'teacher.info_education': 'Education',
    'teacher.info_lessons': 'Lesson Types',
    'teacher.info_availability': 'Availability',
    'teacher.info_hours': 'Working Hours',
    'teacher.info_price': 'Pricing',
    'teacher.info_specializations': 'Specializations',
    'teacher.lang_hebrew': 'Hebrew',
    'teacher.lang_english': 'English',
    'teacher.lang_russian': 'Russian',
    'teacher.lang_french': 'French',
    'teacher.lang_spanish': 'Spanish',
    'teacher.lang_arabic': 'Arabic',
    'teacher.audience_children': 'Children',
    'teacher.audience_teenagers': 'Teenagers',
    'teacher.audience_adults': 'Adults',
    'teacher.audience_seniors': 'Seniors',
    'teacher.audience_beginners': 'Beginners',
    'teacher.audience_intermediate': 'Intermediate',
    'teacher.audience_advanced': 'Advanced',
    'teacher.audience_professional': 'Professional',
    'teacher.social_website': 'Website',
    'teacher.social_link': 'Link',
    'teacher.video_caption': 'Introduction Video',
    'teacher.whatsapp_msg': 'Hi, I found you on Acordiskate',

    // Articles list
    'articles.all_title': 'All Articles',
    'articles.search_placeholder': 'Search...',
    'articles.all_categories': 'All Categories',
    'articles.all_types': 'All Types',
    'articles.count_suffix': 'articles',
    'articles.no_results': 'No Articles Found',
    'articles.cat_general': 'General',
    'articles.cat_news': 'News',
    'articles.cat_reviews': 'Reviews',
    'articles.cat_interviews': 'Interviews',
    'articles.cat_features': 'Features',
    'articles.cat_live': 'Live Reports',
    'articles.cat_album_reviews': 'Album Reviews',
    'articles.cat_music_tech': 'Music Technology',
    'articles.cat_education': 'Music Education',
    'articles.cat_popular': 'Popular',
    'articles.cat_clips': 'Clips',
    'articles.cat_blog': 'Blog',
    'articles.cat_opinion': 'Opinion',
    'articles.cat_charts': 'Charts',
    'articles.cat_behind': 'Behind the Scenes',
    'articles.type_news': 'News',
    'articles.type_blog': 'Blog',

    // Tuner mic errors
    'tuner.mic_denied': 'Microphone access denied. Enable access in browser settings and try again.',
    'tuner.mic_error': 'Cannot access microphone. Check it is connected and try again.',

    // Chord dictionary extras
    'dict.no_bass': 'No Bass',
    'dict.finger_name_1': 'Index Finger',

    // Artist create form
    'artist_create.badge': 'Artist Page',
    'artist_create.step_profile': 'Profile',
    'artist_create.step_links': 'Links',
    'artist_create.step_media': 'Media',
    'artist_create.form_steps': 'Form Steps',
    'artist_create.success_title': 'Artist page submitted for review',
    'artist_create.success_text': 'Details sent to admin. You can now proceed to choose a plan to unlock advanced features.',
    'artist_create.choose_plan': 'Choose Plan',
    'artist_create.finish': 'Done',
    'artist_create.step1_intro': 'Let\'s start from the heart of the profile.',
    'artist_create.step1_title': 'Initial Profile',
    'artist_create.step1_desc': 'Photo, name and intro content for a clear first impression.',
    'artist_create.profile_photo_label': 'Profile Photo',
    'artist_create.profile_photo_hint': 'A clear photo that will be the face of your page.',
    'artist_create.paste_photo_url': 'Paste image URL here',
    'artist_create.name_he': 'Hebrew Name',
    'artist_create.name_he_placeholder': 'Artist name in Hebrew *',
    'artist_create.name_en': 'English Name',
    'artist_create.banner_label': 'Header Image',
    'artist_create.banner_hint': 'Wide background at the top of the page. Recommended: 1920x400.',
    'artist_create.banner_media_type': 'Banner Media Type',
    'artist_create.banner_image': 'Static Image',
    'artist_create.banner_gif': 'GIF / Animation',
    'artist_create.paste_banner_url': 'Paste banner URL here',
    'artist_create.paste_gif_url': 'Paste GIF or short video URL here',
    'artist_create.short_desc_label': 'Short Description',
    'artist_create.short_desc_placeholder': 'Short description: a sentence or two about who you are and your sound.',
    'artist_create.bio_label': 'Biography',
    'artist_create.bio_placeholder': 'Biography: share your journey, influences, work and highlights.',
    'artist_create.step2_desc': 'Connect your page to the world beyond the site, clearly and cleanly.',
    'artist_create.website_sr': 'Personal Website',
    'artist_create.website_placeholder': 'Personal website - https://example.com',
    'artist_create.social_kicker': 'Social Networks',
    'artist_create.social_desc': 'Links that go straight to your active social pages.',
    'artist_create.music_kicker': 'Music Platforms',
    'artist_create.music_desc': 'Direct links for listening, viewing and quick access.',
    'artist_create.step3_desc': 'Live gallery, videos and promotional content, organized lightly.',
    'artist_create.gallery_kicker': 'Media Gallery',
    'artist_create.gallery_desc': 'A photo collection that expands your visual story.',
    'artist_create.add_image': 'Add Image',
    'artist_create.add_image_hint': 'New block for gallery',
    'artist_create.add_video': 'Add Video',
    'artist_create.add_video_hint': 'Part of the extended gallery',
    'artist_create.remove_image': 'Remove Image',
    'artist_create.gallery_img_alt': 'Gallery image',
    'artist_create.caption_placeholder': 'Short caption, if needed',
    'artist_create.remove_video': 'Remove Video',
    'artist_create.video_title_placeholder': 'Video title',
    'artist_create.paste_video_url': 'Paste video URL here',
    'artist_create.performance_kicker': 'Performance',
    'artist_create.performance_desc': 'If there\'s a performance to promote, add a block here after the gallery.',
    'artist_create.perf_banner_label': 'Performance Banner',
    'artist_create.perf_banner_hint': 'Recommended: a wide image that clearly shows the performance.',
    'artist_create.perf_banner_placeholder': 'Paste performance banner URL here',
    'artist_create.perf_ticket_placeholder': 'Ticket purchase link',
    'artist_create.perf_show_banner': 'Show performance banner on artist page',
    'artist_create.back_to_chat': 'Back to Chat',
    'artist_create.prev': 'Back',
    'artist_create.next': 'Continue',
    'artist_create.submit': 'Submit',
    'artist_create.platform_instagram': 'Paste Instagram link',
    'artist_create.platform_facebook': 'Paste Facebook link',
    'artist_create.platform_tiktok': 'Paste TikTok link',
    'artist_create.platform_twitter': 'Paste X / Twitter link',
    'artist_create.platform_youtube': 'Paste YouTube link',
    'artist_create.platform_spotify': 'Paste Spotify link',
    'artist_create.platform_zing': 'Paste Zing link',

    // Add song modal
    'song_modal.edit_title': 'Edit Song',
    'song_modal.add_title': 'Add New Song',
    'song_modal.add_short': 'Add Song',
    'song_modal.close_continue': 'You can close this window or continue from here.',
    'song_modal.which_song': 'Which song would you like to add?',
    'song_modal.song_ready': 'Name and image are ready — let\'s add the lyrics and chords.',
    'song_modal.change_song': 'Choose a different song',
    'song_modal.song_exists': 'This song already exists in the system',
    'song_modal.go_to_song': 'Go to song page',
    'song_modal.wrong_song': 'That\'s not the song I meant',
    'song_modal.not_found_manual': 'Didn\'t find it?',
    'song_modal.paste_yt_manual': 'Paste a YouTube link manually',
    'song_modal.full_manual': 'Full manual entry',
    'song_modal.full_manual_hint': 'Switch to the old form without a YouTube link',
    'song_modal.paste_yt_ok': 'No problem, paste a YouTube link here and we\'ll continue.',
    'song_modal.song_title_input': 'Enter song name here',
    'song_modal.paste_yt_link': 'Paste YouTube link here',
    'song_modal.invalid_yt': 'Please paste a valid YouTube link',
    'song_modal.paste_link_manual': 'Paste a manual link',
    'song_modal.continue_no_link': 'Continue without link',
    'song_modal.auto_id_label': 'Selected for auto-detection',
    'song_modal.add_lyrics_prompt': 'Great. Now just add the lyrics and chords.',
    'song_modal.paste_lyrics': 'Paste the song\'s lyrics and chords here...',
    'song_modal.lyrics_error': 'Please add lyrics and chords to continue',
    'song_modal.sheet_music_label': 'Sheet Music (optional)',
    'song_modal.sheet_music_placeholder': 'Link to sheet music or upload',
    'song_modal.almost_done': 'Almost ready.',
    'song_modal.before_send': 'Before Submitting',
    'song_modal.review_note': 'Quick review — you can update anything.',
    'song_modal.song_name_label': 'Song Name:',
    'song_modal.artist_label': 'Artist:',
    'song_modal.original_key_detected': 'Original Key:',
    'song_modal.easy_key_detected': 'Easy Key:',
    'song_modal.auto_detected': '(auto-detected)',
    'song_modal.song_image_alt': 'Song image',
    'song_modal.song_name_field': 'Song Name *',
    'song_modal.song_title_placeholder': 'Song name',
    'song_modal.yt_link_field': 'YouTube Link *',
    'song_modal.yt_placeholder': 'YouTube link',
    'song_modal.image_placeholder': 'Image link',
    'song_modal.artists_field': 'Artists *',
    'song_modal.add_artist_placeholder': 'Add artist',
    'song_modal.artist_new': 'New',
    'song_modal.artist_similar': 'We found similar artists. Click to replace.',
    'song_modal.pending_admin': 'Will be sent for admin approval',
    'song_modal.original_key_field': 'Original Key *',
    'song_modal.select_key': 'Select key',
    'song_modal.easy_key_field': 'Easy Key',
    'song_modal.select_easy_key': 'Select easy key',
    'song_modal.preview_edit': 'Edit',
    'song_modal.save_changes': 'Save Changes',
    'song_modal.saving': 'Saving...',
    'song_modal.submit_approval': 'Submit for Approval',
    'song_modal.prev': 'Back',
    'song_modal.next': 'Next',
    'song_modal.preview_next': 'Preview and Approve',
    'song_modal.song_details': 'Song Details:',
    'song_modal.song_name_req': 'Song Name *',
    'song_modal.song_name_placeholder_legacy': 'Enter song name',
    'song_modal.yt_searching': 'Searching YouTube...',
    'song_modal.yt_hint': 'You can select a result to auto-fill the link, image and artist name.',
    'song_modal.yt_result_alt': 'YouTube result',
    'song_modal.yt_autofill': 'Auto-fill',
    'song_modal.yt_autofilled': 'YouTube video selected — basic details auto-filled.',
    'song_modal.yt_artist_suggested': 'Suggested artist:',
    'song_modal.duplicate_warning': '⚠️ Similar songs found:',
    'song_modal.title_error': 'Song name is required (2-120 characters)',
    'song_modal.artists_label_legacy': 'Artists (up to 5) *',
    'song_modal.add_artist_legacy': 'Add artist...',
    'song_modal.similar_artists_prefix': 'We found similar artists to',
    'song_modal.similar_artists_q': 'Would you like to choose one?',
    'song_modal.no_match_prefix': 'No sure match found for',
    'song_modal.no_match_new': 'You can add them as a new artist.',
    'song_modal.new_artist': 'This is a new artist',
    'song_modal.add_as_new': 'Add as new artist',
    'song_modal.add_new_artist_prefix': 'Add new artist: ',
    'song_modal.pending_admin_warning': '⚠️ Will be sent for admin approval',
    'song_modal.artists_error': 'You must add at least one artist',
    'song_modal.composer_label': 'Composer',
    'song_modal.add_composer': 'Add composer (optional)...',
    'song_modal.add_new_composer_prefix': 'Add new composer: ',
    'song_modal.pending_admin_review': '⚠️ Will be reviewed by admin',
    'song_modal.yt_link_label': 'YouTube Link *',
    'song_modal.spotify_label': 'Spotify Link',
    'song_modal.paste_image': 'Paste image link',
    'song_modal.tags_label': 'Tags',
    'song_modal.add_tag': 'Add tag...',
    'song_modal.add_new_tag_prefix': 'Add new tag: ',
    'song_modal.genres_label': 'Genres',
    'song_modal.add_genre': 'Add genre...',
    'song_modal.add_new_genre_prefix': 'Add new genre: ',
    'song_modal.content_header': 'Lyrics & Chords',
    'song_modal.lyrics_placeholder_legacy': 'Write the lyrics and chords here *',
    'song_modal.lyrics_error_legacy': 'Required (minimum 10 characters)',
    'song_modal.auto_detect': 'Auto-detect',
    'song_modal.auto_detected_key': 'Auto-detected:',
    'song_modal.key_error': 'Please select the original key',
    'song_modal.easy_key_label': 'Easy Play Key',
    'song_modal.preview_title': 'Preview',
    'song_modal.preview_check_edit': 'Review changes before saving',
    'song_modal.preview_check_new': 'Review details before uploading',
    'song_modal.tag_for_profile': 'Assign content to public profile',
    'song_modal.tag_myself': 'Tag content under your name',
    'song_modal.tag_myself_yes': 'Yes, tag under my name',
    'song_modal.filter_all': 'All',
    'song_modal.filter_teachers': 'Teachers',
    'song_modal.filter_providers': 'Service Providers',
    'song_modal.filter_artists': 'Artists',
    'song_modal.filter_users': 'Regular Members',
    'song_modal.sort_name': 'Sort by Name',
    'song_modal.sort_type': 'Sort by Type',
    'song_modal.search_profile': 'Search by artist / teacher / professional name...',
    'song_modal.no_results': 'No results found',
    'song_modal.approved_label': 'Approved for publication (admin only)',
    'song_modal.back': 'Back',
    'song_modal.cancel': 'Cancel',
    'song_modal.send_approval': 'Submit for Approval',
    'song_modal.save_edit': 'Save Changes',
    'song_modal.publish_song': 'Publish Song',
    'song_modal.success_updated': 'Song updated successfully',
    'song_modal.success_sent': 'Sent for admin review',
    'song_modal.error_update': 'An error occurred while updating the song',
    'song_modal.error_save': 'An error occurred while saving the song',
    'song_modal.smart_step1_title': 'Let\'s start by finding the song',
    'song_modal.smart_step2_title': 'Add lyrics and chords',
    'song_modal.smart_step3_title': 'Review before submitting',
    'song_modal.smart_step1_desc': 'Type a song name or paste a link, and I\'ll set up the basics.',
    'song_modal.smart_step2_desc': 'Paste the content, and I\'ll detect the key and prepare the view.',
    'song_modal.smart_step3_desc': 'One last look at the details before submitting.',
    'song_modal.helper_wrong_song': 'If this isn\'t the right song, you can choose another.',
    'song_modal.helper_searching_yt': 'Searching YouTube results now...',
    'song_modal.helper_loading_meta': 'Fetching the image and details from the link.',
    'song_modal.helper_no_results': 'No good match found. Try rephrasing or paste a YouTube link manually.',
    'song_modal.helper_detecting_key': 'Detecting the original key and easy key now.',
    'song_modal.preview_ready': 'Almost ready. Review the details and submit for approval.',
    'song_modal.preview_ready_pre': 'Almost ready. Reviewing',
    'song_modal.preview_ready_suf': 'and submitting for approval.',
    'song_modal.action_preview': 'Review & Preview',
    'song_modal.profile_artist': 'Artist',
    'song_modal.profile_user': 'Regular Member',
    'song_modal.profile_teacher': 'Teacher',
    'song_modal.profile_service': 'Service Provider',
    'song_modal.profile_pro': 'Teacher / Professional',
    'song_modal.not_linked': ' · Not linked to an account',
    'song_modal.success_add': 'Sent for admin approval. Thank you.',
    'song_modal.error_prefix': 'Error',
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly STORAGE_KEY = 'app_lang';

  private langSubject = new BehaviorSubject<Lang>(this.getInitialLang());
  lang$ = this.langSubject.asObservable();

  constructor() {
    this.applyLang(this.langSubject.value);
  }

  get currentLang(): Lang {
    return this.langSubject.value;
  }

  setLang(lang: Lang): void {
    localStorage.setItem(this.STORAGE_KEY, lang);
    this.langSubject.next(lang);
    this.applyLang(lang);
  }

  toggle(): void {
    this.setLang(this.currentLang === 'he' ? 'en' : 'he');
  }

  translate(key: string): string {
    return TRANSLATIONS[this.currentLang][key] ?? key;
  }

  private getInitialLang(): Lang {
    return 'he';
  }

  private applyLang(lang: Lang): void {
    const html = document.documentElement;
    html.lang = lang;
    html.dir = lang === 'he' ? 'rtl' : 'ltr';
  }
}
