// <auto-generated />
using AkordishKeit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AkordishKeit.Migrations
{
    [DbContext(typeof(AkordishKeitDbContext))]
    [Migration("20260409170000_AddMissingColumnsFromSkippedMigrations")]
    partial class AddMissingColumnsFromSkippedMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // minimal snapshot — not used for running migrations
        }
    }
}
