// <auto-generated />
using AkordishKeit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AkordishKeit.Migrations
{
    [DbContext(typeof(AkordishKeitDbContext))]
    [Migration("20260413000001_AddFullTextIndexOnSongsTitle")]
    partial class AddFullTextIndexOnSongsTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // minimal snapshot — no EF model changes in this migration
        }
    }
}
