import type { ComponentLibraryItem } from '../component-library.types';
import { SECTION_TITLES_LIBRARY_ITEM } from './section-titles.block';
import { BANNERS_LIBRARY_ITEM } from './banners.block';
import { RECOMMENDATION_LIBRARY_ITEM } from './recommendations.block';
import { CONTINUE_LINKS_LIBRARY_ITEM } from './continue-links.block';
import {
  SPACER_LIBRARY_ITEM,
  DIVIDER_LIBRARY_ITEM,
  BRANDED_SECTION_LIBRARY_ITEM,
  TWO_COLUMNS_LIBRARY_ITEM,
  BRANDED_TEXT_LIBRARY_ITEM,
  PERSONAL_OPENING_LIBRARY_ITEM,
  SIGNATURE_LIBRARY_ITEM,
  BRANDED_FOOTER_LIBRARY_ITEM,
  UNSUBSCRIBE_LIBRARY_ITEM,
} from './structure-blocks';

export const ALL_SYSTEM_BLOCKS: ComponentLibraryItem[] = [
  SECTION_TITLES_LIBRARY_ITEM,
  BANNERS_LIBRARY_ITEM,
  RECOMMENDATION_LIBRARY_ITEM,
  CONTINUE_LINKS_LIBRARY_ITEM,
  SPACER_LIBRARY_ITEM,
  DIVIDER_LIBRARY_ITEM,
  BRANDED_SECTION_LIBRARY_ITEM,
  TWO_COLUMNS_LIBRARY_ITEM,
  BRANDED_TEXT_LIBRARY_ITEM,
  PERSONAL_OPENING_LIBRARY_ITEM,
  SIGNATURE_LIBRARY_ITEM,
  BRANDED_FOOTER_LIBRARY_ITEM,
  UNSUBSCRIBE_LIBRARY_ITEM,
];
